"""Emitter: demo SoT -> web app generated seed modules.

The mapping contract below is authoritative; this module codegens it with zero
runtime design decisions (pure function of the SoT).

OUTPUT PATH(S)
  web/src/data/seeds/account.generated.ts
  web/src/data/seeds/vocabulary.generated.ts
  (a single combined `*.generated.ts` per domain; the hand-authored
  account.seed.ts / vocabulary.seed.ts now RE-EXPORT from these generated files,
  which are the new import target via seeds/index.ts.)

  All generated files carry a `// GENERATED by ops/demo/build_demo.py — do not
  edit` banner; `check=True` re-emits to a string and byte-compares against the
  committed file, exit 1 on drift.

MAPPING  (SoT key  ->  web export)
  ACCOUNT  (from identity)
    ACCOUNT_SEED.userId          <- identity.user_id
    ACCOUNT_SEED.email           <- identity.email
    ACCOUNT_SEED.displayName     <- identity.display_name
    ACCOUNT_SEED.accessToken     <- identity.access_token
    ACCOUNT_SEED.linkedIds       <- [identity.provider_user_id]
    ACCOUNT_SEED.deletedDirs     <- ["/data/users/" + identity.user_id]
    SEED_NOW_ISO                 <- dataset.review_anchor   (single synthetic "now")

  NOTEBOOKS  (from dataset.notebooks, JOIN KEY = notebook NAME)
    For the implicit "default" notebook (sortOrder 0, isDefault true, legacy
    name/color preserved) plus each dataset notebook (declared order,
    sortOrder = index+1):
      NotebookSeed.id            <- slug(name)            (stable id from NAME)
      NotebookSeed.name          <- notebook.name
      NotebookSeed.color         <- notebook.color
      NotebookSeed.coverPattern  <- notebook.cover_pattern
      NotebookSeed.cardCount     <- count of dataset.cards whose notebook == name
    The implicit default notebook is always emitted (isDefault true) for parity
    with the legacy shape; cardCount = count of cards targeting "default" (0 in
    this dataset, since every card lives in a named notebook).

  VOCAB CARDS  (from dataset.cards)
    VocabCardSeed.id             <- "card-" + (1-based index)
    VocabCardSeed.word           <- card.content
    VocabCardSeed.meaning        <- card.meaning
    VocabCardSeed.pos            <- strip-dot(card.pos)   ("n." -> "n", null -> null)
    VocabCardSeed.notebookId     <- slug(card.notebook)   (NAME -> same id as above)

  GRAPH LINKS  (from dataset.links)
    GraphLinkSeed.id             <- "link-" + (1-based index)
    GraphLinkSeed.fromId         <- id of the card whose content == link.from within link.notebook
    GraphLinkSeed.toId           <- id of the card whose content == link.to within link.notebook
    GraphLinkSeed.kind           <- link.kind
    GraphLinkSeed.confidence     <- link.confidence
    GraphLinkSeed.reason         <- link.reason
    GraphLinkSeed.hidden         <- false
    GraphLinkSeed.notebookId     <- slug(link.notebook)

  REVIEW EVENT LOG  (synthetic window params; anchored to review_anchor)
    REVIEW_EVENT_LOG_SEED.anchorIso   <- dataset.review_anchor
    REVIEW_EVENT_LOG_SEED.words       <- first 5 card.content (deterministic sample)
    REVIEW_EVENT_LOG_SEED.notebookId  <- "default"  (legacy: events live in default)
    REVIEW_EVENT_LOG_SEED.windowDays  <- 42 (preserve legacy default)
    (the deterministic 42-day generation stays in the web transformer.)

slug(name): lower-case, non-alphanumerics -> "-", collapse repeats, trim "-".
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from .sot import DemoSoT

# ── output targets ──────────────────────────────────────────────────────────
# emit_web lives in ops/demo/; the web seed tree is ../../web/src/data/seeds.
_HERE = Path(__file__).resolve().parent
_REPO_ROOT = _HERE.parent.parent
_SEEDS_DIR = _REPO_ROOT / "web" / "src" / "data" / "seeds"
ACCOUNT_GENERATED_PATH = _SEEDS_DIR / "account.generated.ts"
VOCAB_GENERATED_PATH = _SEEDS_DIR / "vocabulary.generated.ts"

_BANNER = (
    "// GENERATED by ops/demo/build_demo.py — do not edit.\n"
    "// Source of truth: ops/demo/demo_identity.json + demo_dataset.json.\n"
    "// Regenerate: (cd backend && uv run python ../ops/demo/build_demo.py emit-web --commit)\n"
)

# Non-SoT defaults preserved verbatim from the legacy seed (stable, not derived).
_NOTEBOOK_DEFAULT_COLOR = "#AFC2D3"
_DEFAULT_NOTEBOOK_NAME = "我的單字本"
_CARD_DEFAULT_INTERVAL_HOURS = "12.0"  # emitted as a float literal
_REVIEW_WINDOW_DAYS = 42
_REVIEW_SAMPLE_WORDS = 5
_DEFAULT_NOTEBOOK_ID = "default"


# ── helpers ─────────────────────────────────────────────────────────────────
def _slug(name: str) -> str:
    """lower-case, non-alphanumerics -> '-', collapse repeats, trim '-'."""
    s = re.sub(r"[^a-z0-9]+", "-", name.lower())
    return s.strip("-")


def _strip_dot(pos: Any) -> str | None:
    """'n.' -> 'n'; None/'' -> None."""
    if pos is None:
        return None
    s = str(pos).strip()
    if not s:
        return None
    return s.rstrip(".")


def _ts_str(value: str) -> str:
    """A TS single-quoted string literal (JSON-escaped, single-quote-safe)."""
    # json.dumps gives us correct escaping for backslash / quote / control / unicode
    # passthrough; we use single quotes to match the seed style, so escape ' and
    # unescape the JSON double quotes we don't need.
    inner = json.dumps(value, ensure_ascii=False)[1:-1]  # strip surrounding ""
    inner = inner.replace("\\\"", '"').replace("'", "\\'")
    return f"'{inner}'"


def _ts_str_or_null(value: Any) -> str:
    return "null" if value is None else _ts_str(str(value))


def _ts_num(value: float | int) -> str:
    """Render a number the way the TS source did (ints stay ints, floats keep
    their decimal form). The dataset confidences are authored as e.g. 0.74."""
    if isinstance(value, bool):  # guard: bool is an int subclass
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    # float: use repr to keep the authored precision; strip a trailing '.0'
    # only when the SoT itself wrote an integer-valued float (none here).
    return repr(float(value))


# ── model derivation (pure) ─────────────────────────────────────────────────
def _derive(sot: DemoSoT) -> dict[str, Any]:
    """Turn the validated SoT into the flat web-seed model the templates render."""
    identity = sot.identity
    dataset = sot.dataset

    now_iso = dataset["review_anchor"]

    account = {
        "userId": identity["user_id"],
        "email": identity["email"],
        "displayName": identity["display_name"],
        "linkedIds": [identity["provider_user_id"]],
        "deletedDirs": [f"/data/users/{identity['user_id']}"],
        "accessToken": identity["access_token"],
    }

    cards = dataset["cards"]

    # cardCount per notebook NAME (named notebooks) + the implicit default bucket.
    count_by_nb: dict[str, int] = {}
    for c in cards:
        nb = c.get("notebook", _DEFAULT_NOTEBOOK_ID)
        count_by_nb[nb] = count_by_nb.get(nb, 0) + 1

    notebooks: list[dict[str, Any]] = [
        {
            "id": _DEFAULT_NOTEBOOK_ID,
            "name": _DEFAULT_NOTEBOOK_NAME,
            "color": _NOTEBOOK_DEFAULT_COLOR,
            "coverPattern": None,
            "sortOrder": 0,
            "isDefault": True,
            "cardCount": count_by_nb.get(_DEFAULT_NOTEBOOK_ID, 0),
        }
    ]
    for idx, nb in enumerate(dataset["notebooks"]):
        name = nb["name"]
        notebooks.append(
            {
                "id": _slug(name),
                "name": name,
                "color": nb.get("color"),
                "coverPattern": nb.get("cover_pattern"),
                "sortOrder": idx + 1,
                "isDefault": False,
                "cardCount": count_by_nb.get(name, 0),
            }
        )

    # card id index: 1-based global order; build a (notebook NAME, content) -> id map
    # for the link join (links reference content within their notebook).
    vocab_cards: list[dict[str, Any]] = []
    id_by_nb_content: dict[tuple[str, str], str] = {}
    for i, c in enumerate(cards, start=1):
        card_id = f"card-{i}"
        nb_name = c.get("notebook", _DEFAULT_NOTEBOOK_ID)
        nb_id = _DEFAULT_NOTEBOOK_ID if nb_name == _DEFAULT_NOTEBOOK_ID else _slug(nb_name)
        vocab_cards.append(
            {
                "id": card_id,
                "word": c["content"],
                "meaning": c["meaning"],
                "pos": _strip_dot(c.get("pos")),
                "notebookId": nb_id,
            }
        )
        id_by_nb_content[(nb_name, c["content"])] = card_id

    links: list[dict[str, Any]] = []
    for i, lk in enumerate(dataset.get("links", []), start=1):
        nb_name = lk.get("notebook", _DEFAULT_NOTEBOOK_ID)
        nb_id = _DEFAULT_NOTEBOOK_ID if nb_name == _DEFAULT_NOTEBOOK_ID else _slug(nb_name)
        links.append(
            {
                "id": f"link-{i}",
                "fromId": id_by_nb_content[(nb_name, lk["from"])],
                "toId": id_by_nb_content[(nb_name, lk["to"])],
                "kind": lk["kind"],
                "confidence": lk["confidence"],
                "reason": lk["reason"],
                "hidden": False,
                "notebookId": nb_id,
            }
        )

    review_words = [c["content"] for c in cards[:_REVIEW_SAMPLE_WORDS]]

    return {
        "nowIso": now_iso,
        "account": account,
        "notebooks": notebooks,
        "vocabCards": vocab_cards,
        "graphLinks": links,
        "reviewWords": review_words,
    }


# ── TS rendering (pure) ─────────────────────────────────────────────────────
def _render_account_ts(model: dict[str, Any]) -> str:
    notebook_rows = []
    for n in model["notebooks"]:
        notebook_rows.append(
            "  { "
            f"id: {_ts_str(n['id'])}, "
            f"name: {_ts_str(n['name'])}, "
            f"color: {_ts_str_or_null(n['color'])}, "
            f"coverPattern: {_ts_str_or_null(n['coverPattern'])}, "
            f"sortOrder: {n['sortOrder']}, "
            f"isDefault: {'true' if n['isDefault'] else 'false'}, "
            f"cardCount: {n['cardCount']} "
            "},"
        )
    notebook_block = "\n".join(notebook_rows)

    a = model["account"]
    linked = ", ".join(_ts_str(x) for x in a["linkedIds"])
    dirs = ", ".join(_ts_str(x) for x in a["deletedDirs"])

    return f"""{_BANNER}//
// Account + notebook domain — codegen from the demo SoT (identity + dataset).
// Holds DOMAIN values only; the hand-authored account.seed.ts re-exports these
// and the API-response shaping lives in ../transformers.

/** Shared synthetic "now" — every seed anchors timestamps here (= review_anchor). */
export const SEED_NOW_ISO = {_ts_str(model['nowIso'])}

/** Default notebook color for notebooks without an authored color. */
export const NOTEBOOK_DEFAULT_COLOR = {_ts_str(_NOTEBOOK_DEFAULT_COLOR)}

export interface NotebookSeed {{
  id: string
  name: string
  color: string | null
  coverPattern: string | null
  sortOrder: number
  isDefault: boolean
  /** Authored card count for this notebook (drives NotebookResponse.cardCount). */
  cardCount: number
}}

/**
 * Demo notebooks. The implicit default notebook (sortOrder 0, isDefault) leads,
 * followed by each dataset notebook in declared order. `cardCount` is the number
 * of dataset cards assigned to that notebook by NAME.
 */
export const NOTEBOOK_SEEDS: NotebookSeed[] = [
{notebook_block}
]

export interface AccountSeed {{
  userId: string
  email: string | null
  displayName: string | null
  /** Linked auth identities — used by the delete-account summary. */
  linkedIds: string[]
  /** Data dirs purged on account deletion (delete-account summary). */
  deletedDirs: string[]
  /** Deterministic access token the mock /auth/verify mints. */
  accessToken: string
}}

export const ACCOUNT_SEED: AccountSeed = {{
  userId: {_ts_str(a['userId'])},
  email: {_ts_str_or_null(a['email'])},
  displayName: {_ts_str_or_null(a['displayName'])},
  linkedIds: [{linked}],
  deletedDirs: [{dirs}],
  accessToken: {_ts_str(a['accessToken'])},
}}
"""


def _render_vocabulary_ts(model: dict[str, Any]) -> str:
    card_rows = []
    for c in model["vocabCards"]:
        card_rows.append(
            "  { "
            f"id: {_ts_str(c['id'])}, "
            f"word: {_ts_str(c['word'])}, "
            f"meaning: {_ts_str(c['meaning'])}, "
            f"pos: {_ts_str_or_null(c['pos'])}, "
            f"notebookId: {_ts_str(c['notebookId'])} "
            "},"
        )
    card_block = "\n".join(card_rows)

    link_rows = []
    for lk in model["graphLinks"]:
        link_rows.append(
            "  { "
            f"id: {_ts_str(lk['id'])}, "
            f"fromId: {_ts_str(lk['fromId'])}, "
            f"toId: {_ts_str(lk['toId'])}, "
            f"kind: {_ts_str(lk['kind'])}, "
            f"confidence: {_ts_num(lk['confidence'])}, "
            f"reason: {_ts_str(lk['reason'])}, "
            f"hidden: {'true' if lk['hidden'] else 'false'}, "
            f"notebookId: {_ts_str(lk['notebookId'])} "
            "},"
        )
    link_block = "\n".join(link_rows)

    words = ", ".join(_ts_str(w) for w in model["reviewWords"])

    return f"""{_BANNER}//
// Vocabulary domain — codegen from the demo SoT (dataset cards / links). Holds
// DOMAIN values only; the hand-authored vocabulary.seed.ts re-exports these and
// the API-response shaping lives in ../transformers.

import {{ SEED_NOW_ISO }} from './account.generated'

/** Default per-card review interval (hours) for freshly-added unlearned cards. */
export const CARD_DEFAULT_INTERVAL_HOURS = {_CARD_DEFAULT_INTERVAL_HOURS}

export interface VocabCardSeed {{
  /** Stable card id (card-1, card-2, …). */
  id: string
  /** Headword (CardResponse.content). */
  word: string
  /** Translation (CardResponse.meaning). */
  meaning: string
  /** Part of speech WITHOUT trailing dot, or null (CardResponse.pos). */
  pos: string | null
  /** Owning notebook id (slug of the dataset notebook NAME). */
  notebookId: string
}}

/** Demo vocab cards, derived 1:1 from dataset.cards (1-based card ids). */
export const VOCAB_CARD_SEEDS: VocabCardSeed[] = [
{card_block}
]

export interface GraphLinkSeed {{
  id: string
  fromId: string
  toId: string
  kind: string
  confidence: number
  reason: string
  hidden: boolean
  notebookId: string
}}

/** Edges between the seeded cards, derived from dataset.links (per-notebook). */
export const GRAPH_LINK_SEEDS: GraphLinkSeed[] = [
{link_block}
]

export interface ReviewEventLogSeed {{
  /** UTC day anchor for the synthetic event window (= SEED_NOW_ISO). */
  anchorIso: string
  /** Words cycled through the synthetic events. */
  words: string[]
  /** Notebook all synthetic events belong to. */
  notebookId: string
  /** Number of trailing days the window spans. */
  windowDays: number
}}

/**
 * Parameters for the synthetic review-event log. The transformer reproduces a
 * deterministic {_REVIEW_WINDOW_DAYS}-day window (skip every 4th day, ramping
 * counts) anchored to SEED_NOW_ISO from these params.
 */
export const REVIEW_EVENT_LOG_SEED: ReviewEventLogSeed = {{
  anchorIso: SEED_NOW_ISO,
  words: [{words}],
  notebookId: {_ts_str(_DEFAULT_NOTEBOOK_ID)},
  windowDays: {_REVIEW_WINDOW_DAYS},
}}
"""


# ── public API ──────────────────────────────────────────────────────────────
def _artifacts(sot: DemoSoT) -> dict[Path, str]:
    model = _derive(sot)
    return {
        ACCOUNT_GENERATED_PATH: _render_account_ts(model),
        VOCAB_GENERATED_PATH: _render_vocabulary_ts(model),
    }


def emit(sot: DemoSoT, *, check: bool = False, commit: bool = False) -> dict:
    """Emit web generated seed modules from the demo SoT.

    Args:
        sot: validated DemoSoT bundle (identity + dataset).
        check: re-emit in memory and byte-compare against the committed
            artifact(s); return a drift report instead of writing.
        commit: write the generated file(s) to disk. When False (and check
            False), this is a dry-run that returns the planned output paths.

    Returns:
        A dict describing the action (paths written / drift verdict).
    """
    artifacts = _artifacts(sot)
    rel = {p: str(p.relative_to(_REPO_ROOT)) for p in artifacts}

    if check:
        drift: list[dict[str, Any]] = []
        for path, expected in artifacts.items():
            if not path.exists():
                drift.append({"path": rel[path], "reason": "missing committed artifact"})
                continue
            actual = path.read_text(encoding="utf-8")
            if actual != expected:
                drift.append({"path": rel[path], "reason": "byte mismatch (regenerate)"})
        return {
            "mode": "check",
            "paths": list(rel.values()),
            "drift": bool(drift),
            "details": drift,
        }

    if commit:
        written: list[str] = []
        for path, content in artifacts.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            written.append(rel[path])
        return {"mode": "commit", "written": written}

    return {"mode": "dry-run", "paths": list(rel.values())}
