// GENERATED by Style Dictionary — DO NOT EDIT
import Foundation

public enum DesignTokens {
    public enum Elevation {
        public static let darkBoost: CGFloat = 1.8
        public enum Steps {
            public enum Z0 {
                public static let blur: CGFloat = 0
                public static let opacity: CGFloat = 0
                public static let y: CGFloat = 0
            }
            public enum Z1 {
                public static let blur: CGFloat = 4
                public static let opacity: CGFloat = 0.03
                public static let y: CGFloat = 1
            }
            public enum Z2 {
                public static let blur: CGFloat = 10
                public static let opacity: CGFloat = 0.06
                public static let y: CGFloat = 4
            }
            public enum Z3 {
                public static let blur: CGFloat = 18
                public static let opacity: CGFloat = 0.1
                public static let y: CGFloat = 8
            }
            public enum Z4 {
                public static let blur: CGFloat = 28
                public static let opacity: CGFloat = 0.16
                public static let y: CGFloat = 14
            }
        }
    }
    public enum Motion {
        public enum Duration {
            public static let breathing: Double = 2.8
            public static let chip: Double = 0.18
            public static let control: Double = 0.14
            public static let indicator: Double = 0.25
            public static let progress: Double = 0.1
            public static let pulse: Double = 1.4
            public static let quick: Double = 0.15
            public static let subtleBreath: Double = 2.4
        }
        public enum Easing {
            public static let chip: String = "ease-out"
            public static let control: String = "ease-out"
            public static let emphasizedDecelerate: String = "cubic-bezier(0.05, 0.7, 0.1, 1.0)"
            public static let follow: String = "cubic-bezier(0.65, 0.0, 0.35, 1.0)"
            public static let linear: String = "linear"
            public static let quick: String = "ease-out"
        }
        public enum Spring {
            public enum Button {
                public static let damping: CGFloat = 0.7
                public static let response: CGFloat = 0.35
            }
            public enum CelebrationBounce {
                public static let damping: CGFloat = 0.55
                public static let response: CGFloat = 0.4
            }
            public enum ContentReveal {
                public static let damping: CGFloat = 0.82
                public static let response: CGFloat = 0.35
            }
            public enum Emphasized {
                public static let damping: CGFloat = 0.8
                public static let response: CGFloat = 0.35
            }
            public enum FeedbackButton {
                public static let damping: CGFloat = 0.72
                public static let response: CGFloat = 0.22
            }
            public enum ModalSwap {
                public static let damping: CGFloat = 0.85
                public static let response: CGFloat = 0.45
            }
            public enum Press {
                public static let damping: CGFloat = 0.65
                public static let response: CGFloat = 0.25
            }
            public enum Relaxed {
                public static let damping: CGFloat = 0.8
                public static let response: CGFloat = 0.4
            }
            public enum ReviewNavigation {
                public static let damping: CGFloat = 0.86
                public static let response: CGFloat = 0.32
            }
            public enum ReviewReveal {
                public static let damping: CGFloat = 0.88
                public static let response: CGFloat = 0.42
            }
            public enum SheetContentAppear {
                public static let damping: CGFloat = 0.78
                public static let response: CGFloat = 0.3
            }
            public enum Standard {
                public static let damping: CGFloat = 0.75
                public static let response: CGFloat = 0.3
            }
            public enum SwipeFling {
                public static let damping: CGFloat = 1
                public static let response: CGFloat = 0.18
            }
            public enum SwipeSnapBack {
                public static let damping: CGFloat = 0.82
                public static let response: CGFloat = 0.4
            }
            public enum SwipeTracking {
                public static let damping: CGFloat = 0.86
                public static let response: CGFloat = 0.14
            }
            public enum TapFeedback {
                public static let damping: CGFloat = 0.7
                public static let response: CGFloat = 0.18
            }
        }
        public enum TapFeedback {
            public static let opacityDip: CGFloat = 0.92
            public static let scaleDown: CGFloat = 0.97
        }
        public enum Transition {
            public static let contentSwap: String = "opacity 0.2s ease-out, transform 0.2s ease-out"
            public static let panelReveal: String = "transform 0.3s ease-out, opacity 0.25s ease-out"
        }
    }
    public enum Radius {
        public enum Scale {
            public static let lg: CGFloat = 12
            public static let md: CGFloat = 8
            public static let none: CGFloat = 0
            public static let pill: CGFloat = 999
            public static let sm: CGFloat = 6
            public static let xl: CGFloat = 16
            public static let xs: CGFloat = 4
        }
        public enum Semantic {
            public static let card: CGFloat = 8
            public static let chip: CGFloat = 6
            public static let control: CGFloat = 6
            public static let overlay: CGFloat = 8
        }
    }
    public enum Space {
        public enum Scale {
            public static let s1: CGFloat = 4
            public static let s10: CGFloat = 64
            public static let s2: CGFloat = 8
            public static let s3: CGFloat = 12
            public static let s4: CGFloat = 16
            public static let s5: CGFloat = 20
            public static let s6: CGFloat = 24
            public static let s7: CGFloat = 32
            public static let s8: CGFloat = 40
            public static let s9: CGFloat = 48
            public static let hairline: CGFloat = 1
            public static let micro: CGFloat = 2
            public static let tiny: CGFloat = 3
        }
        public enum Semantic {
            public static let actionButtonPaddingV: CGFloat = 13
            public static let cardPadding: CGFloat = 18
            public static let chipPaddingH: CGFloat = 10
            public static let chipPaddingV: CGFloat = 5
            public static let chromeButtonSize: CGFloat = 32
            public static let compactChipPaddingH: CGFloat = 6
            public static let compactChipPaddingV: CGFloat = 3
            public static let dividerAir: CGFloat = 16
            public static let emptyStateStack: CGFloat = 14
            public static let inlineGap: CGFloat = 8
            public static let microGap: CGFloat = 6
            public static let pageHPadding: CGFloat = 20
            public static let progressBarFillMin: CGFloat = 6
            public static let progressBarGap: CGFloat = 5
            public static let progressBarHeight: CGFloat = 5
            public static let progressBarWidth: CGFloat = 104
            public static let rowPaddingV: CGFloat = 9
            public static let sectionGap: CGFloat = 14
            public static let sheetPadding: CGFloat = 24
            public static let tabSelectorHeight: CGFloat = 32
            public static let toneChipPaddingH: CGFloat = 10
            public static let toneChipPaddingV: CGFloat = 6
            public static let toolbarBadgePaddingH: CGFloat = 5
            public static let toolbarBadgePaddingV: CGFloat = 2
        }
    }
    public enum Typography {
        public enum Family {
            public static let display: String = "'CormorantGaramond', 'CrimsonPro', 'Noto Serif TC', 'Songti TC', Georgia, serif"
            public static let italic: String = "'CormorantGaramond', Georgia, serif"
            public static let mono: String = "ui-monospace, 'SF Mono', SFMono-Regular, Menlo, monospace"
            public static let sans: String = "'ElmsSans', 'PingFang TC', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif"
            public static let serif: String = "'CrimsonPro', 'Songti TC', 'Noto Serif TC', Georgia, serif"
        }
        public enum Leading {
            public static let body: CGFloat = 1.5
            public static let caption: CGFloat = 1.3
            public static let display: CGFloat = 1.05
            public static let heading: CGFloat = 1.2
            public static let reading: CGFloat = 1.6
        }
        public enum Scale {
            public static let body: CGFloat = 17
            public static let caption: CGFloat = 12
            public static let caption2: CGFloat = 11
            public static let detailWord: CGFloat = 27
            public static let h1: CGFloat = 28
            public static let h2: CGFloat = 22
            public static let hero: CGFloat = 40
            public static let monoLabel: CGFloat = 10
            public static let rowWord: CGFloat = 18
            public static let sectionTitle: CGFloat = 18
            public static let subhead: CGFloat = 15
        }
        public enum Tracking {
            public static let h2Tight: CGFloat = -0.65
            public static let label: CGFloat = 0.5
            public static let normal: CGFloat = 0
            public static let tight: CGFloat = -1.2
            public static let uppercase: CGFloat = 0.8
            public static let wide: CGFloat = 0.3
        }
    }
}
