#!/usr/bin/env bash
# Source-only: hermetic-test harness for every ops test (P0 2026-10-09,
# docs/runbook/incidents/2026-10-09-kg-data-deleted-by-test.md).
#
# An ops test once reached production (a negative-control loop ran the real
# devops.sh over ssh and `rm -rf`-ed the live data dir).  The rule this file
# enforces is structural, not procedural: an ops test process can never reach a
# remote host unless the test itself installed its own fake on PATH/seam first.
#
#   hermetic_ops_test_init [ROOT]
#     - exports KG_OPS_TEST=1 (devops.sh's transport tripwire keys off it)
#     - prepends a shim dir whose ssh/scp/sftp/rsync/aws print
#         FORBIDDEN: network/production access from an ops test: <argv>
#       to stderr and exit 97
#     - points KG_SSH_CMD / KG_SCP_CMD (devops.sh transport seams) and
#       GIT_SSH_COMMAND at the same deny stub
#     - exports KG_OPS_TEST_TRIPWIRE_LOG: every shim denial and every devops.sh
#       tripwire appends a line, so an attempt is visible even when the test swallowed
#       the exit status (ops/test_ops.sh fails the run when the log is non-empty)
#
# A test that genuinely needs a fake ssh/rsync/aws installs its own stub earlier
# in PATH (or sets its own KG_SSH_CMD) *after* init; those win because they are
# later in PATH / later assignments.  Idempotent: safe to call from the
# aggregate runner and again from a standalone test it spawns.

if [[ -n "${_KG_HERMETIC_OPS_TEST_LOADED:-}" ]]; then
  return 0 2>/dev/null || exit 0
fi
_KG_HERMETIC_OPS_TEST_LOADED=1

# The shim tool names.  Keep in sync with the lint in
# ops/tests/test_ops_hermetic_lint.sh (it only checks the contract, not the list).
HERMETIC_DENY_TOOLS=(ssh scp sftp rsync aws)

_hermetic_write_deny_stub() {  # <path>
  local path="$1" tmp
  tmp="${path}.tmp.$$"
  cat >"$tmp" <<'STUB'
#!/bin/bash
# Generated by ops/lib/hermetic_ops_test.sh — never reaches the network.
# Exception: a lone `--version` / `-V` is a local flavor probe (devops.sh's
# rsync_progress_flags runs `rsync --version`), not network access: hand it to the
# real binary found on PATH minus this shim dir.
# The walk skips every file carrying this generator marker (whatever spelling of the shim
# dir put it on PATH) and a passthrough marker env var stops a shim from re-entering
# another shim: with no real binary anywhere the call is denied, never looped (#2922).
if [ "$#" -eq 1 ] && { [ "$1" = "--version" ] || [ "$1" = "-V" ]; } && [ -z "${KG_HERMETIC_SHIM_PASSTHROUGH:-}" ]; then
  _real=""; _ifs="$IFS"; IFS=:
  for _d in $PATH; do
    _f="$_d/${0##*/}"
    [ -n "$_d" ] && [ -f "$_f" ] && [ -x "$_f" ] || continue
    grep -q 'Generated by ops/lib/hermetic_ops_test.sh' "$_f" 2>/dev/null && continue
    _real="$_f"; break
  done
  IFS="$_ifs"
  [ -n "$_real" ] && KG_HERMETIC_SHIM_PASSTHROUGH=1 exec "$_real" "$1"
fi
_msg="FORBIDDEN: network/production access from an ops test: ${0##*/}"
for _a in "$@"; do _msg="$_msg $_a"; done
printf '%s\n' "$_msg" >&2
# Leave a durable trace even if the caller swallows our exit status (`|| true`,
# `$(...)`, `2>/dev/null`): ops/test_ops.sh fails the whole run when this file is non-empty.
[ -n "${KG_OPS_TEST_TRIPWIRE_LOG:-}" ] && printf '%s\n' "$_msg" >> "$KG_OPS_TEST_TRIPWIRE_LOG" 2>/dev/null
exit 97
STUB
  chmod 755 "$tmp"
  mv -f "$tmp" "$path"
}

hermetic_ops_test_init() {
  local root="${1:-}" dir tool
  if [[ -z "$root" ]]; then
    root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
  fi
  dir="$root/.cache/ops-hermetic-shims"
  # devops.sh splits KG_SSH_CMD on whitespace, so the deny stub path must have none.
  case "$dir" in
    *[[:space:]]*) dir="$(mktemp -d "${TMPDIR:-/tmp}/kg-ops-hermetic.XXXXXX")" ;;
  esac
  mkdir -p "$dir"
  for tool in "${HERMETIC_DENY_TOOLS[@]}"; do
    _hermetic_write_deny_stub "$dir/$tool"
  done
  # Transport seams get a *differently named* deny stub, so devops.sh's
  # tripwire can tell "explicit fake seam" from "real ssh by name".
  _hermetic_write_deny_stub "$dir/kg-deny-transport"

  export KG_OPS_TEST=1
  export KG_OPS_SHIM_DIR="$dir"
  # Every denied attempt (shim) and every devops.sh tripwire appends here.  The aggregate
  # runner truncates it at start and fails the run if it is non-empty at the end.
  # Kept if the parent already set it, so nested standalone tests share one log.
  export KG_OPS_TEST_TRIPWIRE_LOG="${KG_OPS_TEST_TRIPWIRE_LOG:-$dir/tripwire.log}"
  case ":$PATH:" in
    ":$dir:"*) ;;
    *) PATH="$dir:$PATH"; export PATH ;;
  esac
  export KG_SSH_CMD="$dir/kg-deny-transport"
  export KG_SCP_CMD="$dir/kg-deny-transport"
  export GIT_SSH_COMMAND="$dir/kg-deny-transport"
}
