// GENERATED by ops/demo/build_demo.py — do not edit.
// Source of truth: ops/demo/demo_identity.json + demo_dataset.json.
// Regenerate: (cd backend && uv run python ../ops/demo/build_demo.py emit-web --commit)
//
// Vocabulary domain — codegen from the demo SoT (dataset cards / links). Holds
// DOMAIN values only; the hand-authored vocabulary.seed.ts re-exports these and
// the API-response shaping lives in ../transformers.

import { SEED_NOW_ISO } from './account.generated'

/** Default per-card review interval (hours) for freshly-added unlearned cards. */
export const CARD_DEFAULT_INTERVAL_HOURS = 12.0

export interface VocabCardSeed {
  /** Stable card id (card-1, card-2, …). */
  id: string
  /** Headword (CardResponse.content). */
  word: string
  /** Translation (CardResponse.meaning). */
  meaning: string
  /** Part of speech WITHOUT trailing dot, or null (CardResponse.pos). */
  pos: string | null
  /** Owning notebook id (slug of the dataset notebook NAME). */
  notebookId: string
}

/** Demo vocab cards, derived 1:1 from dataset.cards (1-based card ids). */
export const VOCAB_CARD_SEEDS: VocabCardSeed[] = [
  { id: 'card-1', word: 'meticulous', meaning: '一絲不苟的；極為仔細的', pos: 'adj', notebookId: 'editorial-picks' },
  { id: 'card-2', word: 'discerning', meaning: '有洞察力的；能辨別細微差異的', pos: 'adj', notebookId: 'editorial-picks' },
  { id: 'card-3', word: 'evoke', meaning: '喚起；引發（情感或記憶）', pos: 'v', notebookId: 'editorial-picks' },
  { id: 'card-4', word: 'luminous', meaning: '明亮的；清晰動人的（文筆）', pos: 'adj', notebookId: 'editorial-picks' },
  { id: 'card-5', word: 'nuance', meaning: '細微差別；微妙之處', pos: 'n', notebookId: 'editorial-picks' },
  { id: 'card-6', word: 'entropy', meaning: '熵；系統的混亂程度', pos: 'n', notebookId: 'systems-thinking' },
  { id: 'card-7', word: 'cascade', meaning: '一連串；連鎖反應', pos: 'n', notebookId: 'systems-thinking' },
  { id: 'card-8', word: 'coherent', meaning: '連貫的；條理一致的', pos: 'adj', notebookId: 'systems-thinking' },
  { id: 'card-9', word: 'leverage', meaning: '善用；以槓桿放大效果', pos: 'v', notebookId: 'systems-thinking' },
  { id: 'card-10', word: 'feedback', meaning: '回饋；系統輸出反向影響輸入', pos: 'n', notebookId: 'systems-thinking' },
  { id: 'card-11', word: 'cadence', meaning: '節奏；穩定推進的步調', pos: 'n', notebookId: 'creative-practice' },
  { id: 'card-12', word: 'iterate', meaning: '反覆打磨；迭代改進', pos: 'v', notebookId: 'creative-practice' },
  { id: 'card-13', word: 'tactile', meaning: '有觸感的；能喚起手感的', pos: 'adj', notebookId: 'creative-practice' },
  { id: 'card-14', word: 'prototype', meaning: '原型；先做出可驗證的版本', pos: 'n', notebookId: 'creative-practice' },
]

export interface GraphLinkSeed {
  id: string
  fromId: string
  toId: string
  kind: string
  confidence: number
  reason: string
  hidden: boolean
  notebookId: string
}

/** Edges between the seeded cards, derived from dataset.links (per-notebook). */
export const GRAPH_LINK_SEEDS: GraphLinkSeed[] = [
  { id: 'link-1', fromId: 'card-1', toId: 'card-2', kind: 'shares_usage', confidence: 0.74, reason: 'Both describe the careful attention an editor brings to a text.', hidden: false, notebookId: 'editorial-picks' },
  { id: 'link-2', fromId: 'card-3', toId: 'card-4', kind: 'shares_usage', confidence: 0.71, reason: 'Luminous prose is precisely the kind that evokes feeling in a reader.', hidden: false, notebookId: 'editorial-picks' },
  { id: 'link-3', fromId: 'card-2', toId: 'card-5', kind: 'shares_usage', confidence: 0.79, reason: 'A discerning reader is one who can register nuance.', hidden: false, notebookId: 'editorial-picks' },
  { id: 'link-4', fromId: 'card-6', toId: 'card-7', kind: 'shares_usage', confidence: 0.81, reason: 'Both describe how disorder propagates through a system over time.', hidden: false, notebookId: 'systems-thinking' },
  { id: 'link-5', fromId: 'card-7', toId: 'card-8', kind: 'contrasts_with', confidence: 0.64, reason: 'Cascade emphasizes runaway propagation; coherent emphasizes orderly structure.', hidden: false, notebookId: 'systems-thinking' },
  { id: 'link-6', fromId: 'card-10', toId: 'card-9', kind: 'shares_usage', confidence: 0.77, reason: 'Feedback loops are a primary place to leverage a system.', hidden: false, notebookId: 'systems-thinking' },
  { id: 'link-7', fromId: 'card-12', toId: 'card-14', kind: 'shares_usage', confidence: 0.84, reason: 'Both belong to the fast feedback loops of product and design work.', hidden: false, notebookId: 'creative-practice' },
  { id: 'link-8', fromId: 'card-11', toId: 'card-13', kind: 'shares_usage', confidence: 0.68, reason: 'Both point to the felt rhythm and texture of a sustained practice.', hidden: false, notebookId: 'creative-practice' },
]

export interface ReviewEventLogSeed {
  /** UTC day anchor for the synthetic event window (= SEED_NOW_ISO). */
  anchorIso: string
  /** Words cycled through the synthetic events. */
  words: string[]
  /** Notebook all synthetic events belong to. */
  notebookId: string
  /** Number of trailing days the window spans. */
  windowDays: number
}

/**
 * Parameters for the synthetic review-event log. The transformer reproduces a
 * deterministic 42-day window (skip every 4th day, ramping
 * counts) anchored to SEED_NOW_ISO from these params.
 */
export const REVIEW_EVENT_LOG_SEED: ReviewEventLogSeed = {
  anchorIso: SEED_NOW_ISO,
  words: ['meticulous', 'discerning', 'evoke', 'luminous', 'nuance'],
  notebookId: 'default',
  windowDays: 42,
}
