// GENERATED by ops/demo/build_demo.py — do not edit.
// Source of truth: ops/demo/demo_identity.json + demo_dataset.json.
// Regenerate: (cd backend && uv run python ../ops/demo/build_demo.py emit-web --commit)
//
// Account + notebook domain — codegen from the demo SoT (identity + dataset).
// Holds DOMAIN values only; the hand-authored account.seed.ts re-exports these
// and the API-response shaping lives in ../transformers.

/** Shared synthetic "now" — every seed anchors timestamps here (= review_anchor). */
export const SEED_NOW_ISO = '2026-06-11T00:00:00Z'

/** Default notebook color for notebooks without an authored color. */
export const NOTEBOOK_DEFAULT_COLOR = '#AFC2D3'

export interface NotebookSeed {
  id: string
  name: string
  color: string | null
  coverPattern: string | null
  sortOrder: number
  isDefault: boolean
  /** Authored card count for this notebook (drives NotebookResponse.cardCount). */
  cardCount: number
}

/**
 * Demo notebooks. The implicit default notebook (sortOrder 0, isDefault) leads,
 * followed by each dataset notebook in declared order. `cardCount` is the number
 * of dataset cards assigned to that notebook by NAME.
 */
export const NOTEBOOK_SEEDS: NotebookSeed[] = [
  { id: 'default', name: '我的單字本', color: '#AFC2D3', coverPattern: null, sortOrder: 0, isDefault: true, cardCount: 0 },
  { id: 'editorial-picks', name: 'Editorial Picks', color: '#8C6A5D', coverPattern: 'waves', sortOrder: 1, isDefault: false, cardCount: 5 },
  { id: 'systems-thinking', name: 'Systems Thinking', color: '#4F7C73', coverPattern: 'grid', sortOrder: 2, isDefault: false, cardCount: 5 },
  { id: 'creative-practice', name: 'Creative Practice', color: '#B96F5B', coverPattern: 'dots', sortOrder: 3, isDefault: false, cardCount: 4 },
]

export interface AccountSeed {
  userId: string
  email: string | null
  displayName: string | null
  /** Linked auth identities — used by the delete-account summary. */
  linkedIds: string[]
  /** Data dirs purged on account deletion (delete-account summary). */
  deletedDirs: string[]
  /** Deterministic access token the mock /auth/verify mints. */
  accessToken: string
}

export const ACCOUNT_SEED: AccountSeed = {
  userId: 'demo-user',
  email: 'demo@wordnexus.lol',
  displayName: '示範使用者',
  linkedIds: ['apple:demo-user'],
  deletedDirs: ['/data/users/demo-user'],
  accessToken: 'demo-access-token',
}
