"""Embedding storage and similarity search."""

from __future__ import annotations

import json
import logging
import os
import time
from datetime import UTC, datetime
from pathlib import Path

import numpy as np
from openai import OpenAIError

from ._fsutil import fsync_dir as _fsync_dir

logger = logging.getLogger(__name__)


def _fsync_path(path: Path) -> None:
    """fsync a closed file by path so its bytes are durable before a rename.

    ``np.save`` writes and closes the .npy itself (no fd to reach), so we
    reopen read-only purely to fsync. Mirrors the durability guarantee of
    ``kg.graph.persistence._atomic_json_write`` (flush + fsync before replace).
    """
    fd = os.open(path, os.O_RDONLY)
    try:
        os.fsync(fd)
    finally:
        os.close(fd)


EMBEDDING_MODEL = "gemini-embedding-2-preview"
EMBEDDING_DIM = 3072
_EMBED_MAX_RETRIES = 3
_EMBED_BACKOFF_BASE = 2
_COSINE_EPS = 1e-9


class EmbeddingStore:
    """Numpy-based embedding storage with similarity search.

    Disk layout (per notebook ``nb``):
      * ``embeddings_{nb}.npy``         — float32 (N, dim) matrix
      * ``card_ids_{nb}.json``          — list[str] aligned with rows
      * ``embeddings_meta_{nb}.json``   — {"model", "dim", "created_at"}

    The meta sidecar guards against silently loading vectors generated by a
    different model or dim. When ``EMBEDDING_MODEL`` / ``EMBEDDING_DIM`` change
    in env, the old files are renamed ``*.legacy_{model}_{dim}`` and the
    store starts empty; pipeline backfill will re-embed on next run.
    """

    def __init__(
        self,
        embeddings_path: Path,
        ids_path: Path,
        llm,
        *,
        model: str = EMBEDDING_MODEL,
        dim: int = EMBEDDING_DIM,
    ) -> None:
        self.embeddings_path = embeddings_path
        self.ids_path = ids_path
        self.llm = llm
        self.model = model
        self.dim = dim
        self._embeddings: np.ndarray | None = None
        self._ids: list[str] = []
        self._id_set: set[str] = set()
        self._id_pos: dict[str, int] = {}  # card_id -> row index (O(1) lookup)
        self._norms: np.ndarray | None = None  # cached L2 norms
        self._dirty: bool = False
        self._load()

    # ------------------------------------------------------------------
    # Meta sidecar (model/dim guard)
    # ------------------------------------------------------------------
    @property
    def _meta_path(self) -> Path:
        # `embeddings_{nb}.npy` -> `embeddings_meta_{nb}.json`. Falls back to
        # a generic name if the .npy stem doesn't start with "embeddings".
        stem = self.embeddings_path.stem  # e.g. "embeddings_default"
        if stem.startswith("embeddings_"):
            suffix = stem[len("embeddings_"):]
            name = f"embeddings_meta_{suffix}.json"
        elif stem == "embeddings":
            name = "embeddings_meta.json"
        else:
            name = f"{stem}_meta.json"
        return self.embeddings_path.with_name(name)

    def _read_meta(self) -> dict | None:
        try:
            return json.loads(self._meta_path.read_text())
        except (FileNotFoundError, json.JSONDecodeError):
            return None

    def _write_meta(self) -> None:
        self._meta_path.parent.mkdir(parents=True, exist_ok=True)
        payload = {
            "model": self.model,
            "dim": self.dim,
            "created_at": datetime.now(UTC).isoformat(),
        }
        tmp = self._meta_path.with_suffix(".json.tmp")
        # Fsync the temp before replace + the dir after, mirroring _save's
        # durability contract — otherwise an OS/power crash can persist a torn
        # or zero-length sidecar that misattributes the store's model/dim.
        with open(tmp, "w", encoding="utf-8") as f:
            f.write(json.dumps(payload))
            f.flush()
            os.fsync(f.fileno())
        tmp.replace(self._meta_path)
        _fsync_dir(self._meta_path.parent)

    def _quarantine_stale(self, stale_model: str, stale_dim: int) -> None:
        """Rename .npy + ids.json to `.legacy_{model}_{dim}` so a future
        diff/recovery is possible. Failure to rename is non-fatal: we still
        proceed with an empty store."""
        self._quarantine_with_suffix(f".legacy_{stale_model}_{stale_dim}")

    def _quarantine_corrupt(self, reason: str) -> None:
        """Rename .npy + ids.json to `.corrupt_{reason}` after a recoverable
        on-disk corruption (structural row/id desync, dim mismatch, or an
        unreadable/truncated file) so the live names are clear for the
        pipeline to rebuild, and the bad files survive for post-mortem.
        Failure to rename is non-fatal: we still proceed empty."""
        self._quarantine_with_suffix(f".corrupt_{reason}")

    def _quarantine_with_suffix(self, suffix: str) -> None:
        for path in (self.embeddings_path, self.ids_path):
            if path.exists():
                try:
                    path.rename(path.with_name(path.name + suffix))
                except OSError as e:
                    logger.warning(
                        "Failed to quarantine embedding file %s: %s",
                        path, e,
                    )

    def _load(self) -> None:
        """Load vectors + ids from disk, gated by sidecar match.

        Cases:
        * No .npy / no ids → fresh empty store (no sidecar written yet).
        * .npy + ids + matching sidecar → load as-is.
        * .npy + ids + no sidecar (legacy deployment) → assume current
          model/dim, load, and write the sidecar in-place (one-shot migration).
        * .npy + ids + sidecar mismatch → quarantine stale files, log warning,
          start empty. Pipeline backfill will re-embed on next run.
        * .npy + ids structurally corrupt (row/id desync or dim mismatch from
          an interrupted save / partial disk) → quarantine the corrupt files,
          log a warning, start empty. Same degrade-not-crash policy as a meta
          mismatch: a hard ``__init__`` failure would 500 every embedding-
          touching request for the notebook (single-worker deploy: one
          interrupted save wedges it). Pipeline backfill re-embeds next run.
        """
        if not (self.embeddings_path.exists() and self.ids_path.exists()):
            return

        meta = self._read_meta()
        if meta is None:
            # Legacy: trust the on-disk files match the active model/dim,
            # and lock that in by writing the sidecar.
            if self._load_validated():
                self._write_meta()
            return

        stale_model = meta.get("model")
        stale_dim = meta.get("dim")
        if stale_model == self.model and stale_dim == self.dim:
            # Defence in depth: sidecar can lie (corruption / hand-edit /
            # half-finished migration). A structural violation degrades to an
            # empty store rather than surfacing later inside find_similar's
            # cosine math (silent corruption) or add_batch's vstack (cryptic).
            self._load_validated()
            return

        logger.warning(
            "EmbeddingStore meta mismatch at %s: on-disk model=%r dim=%r, "
            "active model=%r dim=%r. Quarantining stale vectors and "
            "starting empty; re-embed will backfill on next pipeline run.",
            self.embeddings_path, stale_model, stale_dim,
            self.model, self.dim,
        )
        self._quarantine_stale(str(stale_model), int(stale_dim) if isinstance(stale_dim, int) else 0)
        # Sidecar must reflect active config now.
        self._write_meta()

    def _load_validated(self) -> bool:
        """Read .npy + ids.json, validate structural consistency, and either
        adopt them into memory or degrade to an empty store.

        Returns True if the on-disk vectors were adopted, False if they were
        quarantined as corrupt and the store was left empty. Never raises for
        a recoverable corruption — all of these degrade identically (log +
        quarantine + empty store), mirroring the meta mismatch path:

        * **Unreadable bytes** — an interrupted ``_save`` can leave the .npy
          or ids.json physically *truncated* (or, on a reused inode, full of
          garbage). ``np.load`` then raises ``ValueError``/``EOFError`` and
          ``json.loads`` raises ``JSONDecodeError``; ``read_text`` can raise
          ``UnicodeDecodeError`` on binary junk. These raise *before* the
          structural checks below ever run, so they must be caught here —
          otherwise the exception escapes ``__init__`` and 500s every
          embedding request for the notebook (single-worker deploy: one
          interrupted save wedges it).
        * **Structural violation** — row/id desync or dim mismatch from a
          half-finished save: caught by ``_shape_dim_violation`` /
          ``_row_id_violation`` below.

        A legal empty store (0-row matrix + ``[]`` ids — the on-disk result
        of removing the last card) passes validation untouched.
        """
        # --- Read + parse, degrading unreadable/truncated files ----------
        # np.load: ValueError ("file seems not fully written?", bad magic,
        # pickled-data refusal), EOFError (0-byte file), OSError (I/O).
        try:
            vectors = np.load(self.embeddings_path)
        except (ValueError, EOFError, OSError) as e:
            return self._degrade_corrupt("npy_unreadable", detail=repr(e))
        # read_text: UnicodeDecodeError on binary garbage. json.loads:
        # JSONDecodeError (a ValueError subclass) on truncated/invalid JSON.
        try:
            ids = json.loads(self.ids_path.read_text())
        except (ValueError, UnicodeDecodeError, OSError) as e:
            return self._degrade_corrupt("ids_json_unreadable", detail=repr(e))

        # --- Structural consistency (#546) -------------------------------
        reason = (
            self._shape_dim_violation(vectors)
            or self._row_id_violation(vectors, ids)
        )
        if reason is not None:
            return self._degrade_corrupt(reason)

        self._embeddings = vectors
        self._ids = ids
        self._id_set = set(self._ids)
        self._id_pos = {cid: i for i, cid in enumerate(self._ids)}
        self._invalidate_norms()
        return True

    def _degrade_corrupt(self, reason: str, *, detail: str | None = None) -> bool:
        """Shared degrade path for any recoverable on-disk corruption: log a
        warning, quarantine the bad files as ``.corrupt_<reason>``, reset to a
        clean empty store, and return False (= vectors NOT adopted).

        Used for both unreadable/truncated files (``np.load`` / ``json.loads``
        raised) and structural violations (row/id desync, dim mismatch). The
        next pipeline run re-embeds to backfill.
        """
        logger.warning(
            "EmbeddingStore corrupt vectors at %s (%s%s): likely an "
            "interrupted save. Quarantining and starting empty; re-embed "
            "will backfill on next pipeline run.",
            self.embeddings_path, reason,
            f"; {detail}" if detail else "",
        )
        self._quarantine_corrupt(reason)
        # Drop any half-loaded state; come up as a clean empty store.
        self._embeddings = None
        self._ids = []
        self._id_set = set()
        self._id_pos = {}
        self._invalidate_norms()
        return False

    def _shape_dim_violation(self, vectors: np.ndarray) -> str | None:
        """Check vectors' shape/dim; return a short reason string on a
        violation, else None.

        Empty matrices (``shape[0] == 0``) are allowed: there is nothing
        to mis-interpret yet, and the next ``add_batch`` will populate
        with the active ``dim``. Anything populated must match ``self.dim``
        exactly — otherwise ``find_similar`` would silently compute cosine
        on stale vectors of a different dim (returns numbers, not crashes),
        which is the precise corruption window we are closing.

        A violation is *recoverable* corruption: callers degrade to an empty
        store (quarantine + re-embed) rather than raising — see ``_load``.
        """
        if vectors.ndim != 2:
            return f"ndim_{vectors.ndim}"
        if vectors.shape[0] > 0 and vectors.shape[1] != self.dim:
            return f"dim_{vectors.shape[1]}_vs_{self.dim}"
        return None

    def _row_id_violation(self, vectors: np.ndarray, ids: list) -> str | None:
        """Check matrix rows vs ids length; return a short reason string on a
        desync, else None.

        ``_save`` writes the ``.npy`` matrix and ``ids.json`` as two separate
        atomic ``replace()`` calls — a crash in between leaves the matrix and
        the id list at different lengths. ``find_similar`` indexes rows by
        ``np.argsort`` position and then maps each index back through
        ``self._ids``; a desynced pair would silently return rows attributed
        to the *wrong* card id (numbers, not a crash).

        Note ``shape[0] == 0`` with ``ids == []`` is the *legal* empty store
        (the on-disk result of removing the last card) and is NOT a violation.
        Like a dim mismatch, a real desync is recoverable corruption: callers
        degrade to an empty store rather than raising — see ``_load``.
        """
        if vectors.shape[0] != len(ids):
            return f"rows_{vectors.shape[0]}_vs_ids_{len(ids)}"
        return None

    def _invalidate_norms(self) -> None:
        self._norms = None

    def _get_norms(self) -> np.ndarray:
        if self._norms is None and self._embeddings is not None:
            self._norms = np.linalg.norm(self._embeddings, axis=1)
        return self._norms

    def _save(self) -> None:
        """Persist matrix + ids to disk.

        The matrix and the id list live in two files, so a save can never be
        fully atomic. We shrink the corruption window as much as possible:
        fully materialise *and fsync* *both* temp files first, then issue the
        two ``replace()`` calls back-to-back so a crash can only land in the
        narrow gap between them. Any residual desync from that gap is caught
        at load time by ``_load_validated`` (via ``_row_id_violation``) and
        degraded to an empty store rather than silently misattributing rows
        in ``find_similar``.

        Durability: each temp file is fsynced before its ``replace()`` (and the
        parent directory fsynced after) so the rename can never be persisted
        ahead of the data on an OS/power crash — otherwise next boot sees a
        zero-length / torn primary file. This mirrors the graph persistence
        standard ``kg.graph.persistence._atomic_json_write``.
        """
        self.embeddings_path.parent.mkdir(parents=True, exist_ok=True)

        # Phase 1: write + fsync both temp files before touching live files.
        tmp_emb: Path | None = None
        if self._embeddings is not None:
            # np.save() auto-appends .npy if missing, so tmp must already end in .npy
            tmp_emb = self.embeddings_path.with_name(self.embeddings_path.stem + "_tmp.npy")
            np.save(tmp_emb, self._embeddings)
            _fsync_path(tmp_emb)
        tmp_ids = self.ids_path.with_suffix(".json.tmp")
        with open(tmp_ids, "w", encoding="utf-8") as f:
            f.write(json.dumps(self._ids))
            f.flush()
            os.fsync(f.fileno())

        # Phase 2: swap into place back-to-back to minimise the desync window.
        if tmp_emb is not None:
            tmp_emb.replace(self.embeddings_path)
        tmp_ids.replace(self.ids_path)
        # Persist the renames (directory entries) too, so the swap survives a
        # crash. Best-effort: a filesystem that rejects dir fsync is tolerated.
        _fsync_dir(self.embeddings_path.parent)

        # Persist (or refresh) the model/dim sidecar alongside the vectors,
        # so a fresh store (no legacy files) still gets a guard on first save.
        if not self._meta_path.exists():
            self._write_meta()

    def _embed(self, texts: list[str]) -> np.ndarray:
        """Get embeddings for one or more texts via a single API call.

        Returns an (N, self.dim) float32 array.
        """
        for attempt in range(_EMBED_MAX_RETRIES):
            try:
                response = self.llm.embed("embed", input=texts, model=self.model)
                # response.data may not be sorted by index; sort to match input order.
                # Gemini's OpenAI-compat layer sometimes returns index=None for
                # the first element — coerce to 0 so sorting doesn't crash.
                sorted_data = sorted(response.data, key=lambda d: d.index if d.index is not None else 0)
                vecs = np.array([d.embedding for d in sorted_data], dtype=np.float32)
                # An empty/truncated upstream batch (``response.data == []`` or
                # per-item embeddings dropped) collapses to a 1-D ``shape (0,)``
                # array. That slips past the dim check below (``shape[1]`` doesn't
                # exist on a 1-D array) and would be assigned straight into
                # ``_embeddings``, only to detonate later inside ``np.vstack`` /
                # ``find_similar`` / ``_get_norms`` with a cryptic AxisError. Reject
                # it here so the failure names the real cause (upstream returned
                # nothing) and ``add_batch`` aborts before mutating ``_ids``.
                if vecs.ndim != 2 or vecs.shape[0] == 0:
                    raise ValueError(
                        f"Empty or malformed embedding response: expected a 2-D "
                        f"(N, {self.dim}) matrix, got shape {vecs.shape} "
                        f"(model={self.model!r}). The upstream returned no usable "
                        f"vectors for {len(texts)} input text(s)."
                    )
                if vecs.shape[1] != self.dim:
                    raise ValueError(
                        f"Embedding dim mismatch: got {vecs.shape[1]}, expected {self.dim} "
                        f"(model={self.model!r}). Check EMBEDDING_DIM env var."
                    )
                return vecs
            except OpenAIError as e:
                if attempt < _EMBED_MAX_RETRIES - 1:
                    time.sleep(_EMBED_BACKOFF_BASE ** attempt)
                    continue
                logger.error("Embedding API error: %s", e, exc_info=True)
                raise e
        raise RuntimeError("unreachable: _embed exhausted retries")

    def add(self, card_id: str, text: str) -> None:
        """Add embedding for a single card (delegates to add_batch)."""
        self.add_batch([(card_id, text)])

    def add_batch(self, items: list[tuple[str, str]]) -> None:
        """Add embeddings for multiple cards in a single API call.

        Items already present are silently skipped. Performs one API call,
        one np.vstack, and one disk save for the entire batch.
        """
        # Filter out already-embedded cards
        new_items = [(cid, text) for cid, text in items if cid not in self._id_set]
        if not new_items:
            return

        new_ids = [cid for cid, _ in new_items]
        new_texts = [text for _, text in new_items]

        vecs = self._embed(new_texts)  # single API call

        if self._embeddings is None:
            self._embeddings = vecs
        else:
            self._embeddings = np.vstack([self._embeddings, vecs])

        base = len(self._ids)
        self._ids.extend(new_ids)
        self._id_set.update(new_ids)
        self._id_pos.update({cid: base + i for i, cid in enumerate(new_ids)})
        self._invalidate_norms()
        self._save()

    def remove(self, card_id: str) -> bool:
        """Evict a single card's vector (delegates to remove_batch).

        Returns True if the card was present and removed, False otherwise.
        """
        return self.remove_batch([card_id]) > 0

    def remove_batch(self, card_ids: list[str]) -> int:
        """Evict multiple cards' vectors in one pass.

        Without this, a deleted card's row lingers in ``_embeddings`` /
        ``_ids`` forever: ``find_similar`` keeps scoring the dead vector and
        can crowd a still-valid candidate out of the top-k. The matrix would
        only ever grow. Cards not present are silently skipped.

        Performs at most one disk save for the whole batch.
        """
        if not card_ids or self._embeddings is None:
            return 0

        to_drop = {cid for cid in card_ids if cid in self._id_set}
        if not to_drop:
            return 0

        keep_mask = np.array(
            [cid not in to_drop for cid in self._ids], dtype=bool
        )
        self._embeddings = self._embeddings[keep_mask]
        self._ids = [cid for cid in self._ids if cid not in to_drop]
        self._id_set = set(self._ids)
        self._id_pos = {cid: i for i, cid in enumerate(self._ids)}
        self._invalidate_norms()
        self._save()
        return len(to_drop)

    def update(self, card_id: str, text: str) -> None:
        """Update existing embedding.

        Only updates the in-memory vector and marks the store dirty.
        Call flush() to persist to disk (e.g. at end of request).
        """
        if card_id not in self._id_set:
            self.add(card_id, text)
            return

        idx = self._id_pos[card_id]
        vecs = self._embed([text])
        self._embeddings[idx] = vecs[0]
        self._invalidate_norms()
        self._dirty = True

    def flush(self) -> None:
        """Persist any dirty (deferred) writes to disk.

        No-op if the store has not been modified since last save.
        """
        if not self._dirty:
            return
        self._save()
        self._dirty = False

    def find_similar(self, card_id: str, k: int = 10) -> list[tuple[str, float]]:
        """Find k most similar cards (excluding self).

        Returns list of (card_id, similarity_score) sorted by similarity descending.
        """
        if self._embeddings is None or card_id not in self._id_set:
            return []

        idx = self._id_pos[card_id]
        query_vec = self._embeddings[idx]

        # Cosine similarity with cached norms
        norms = self._get_norms()
        query_norm = norms[idx]
        similarities = (self._embeddings @ query_vec) / (norms * query_norm + _COSINE_EPS)

        # Top (k+1) selection (the +1 absorbs self, filtered out below).
        # np.argpartition is O(N) vs argsort's O(N log N): for a 10k-row store
        # the full sort is the dominant cost of judge enrichment. We argpartition
        # to a candidate pool, then argsort *only that pool*.
        #
        # Equivalence to a full argsort, precisely: for a *continuous* spectrum
        # (no exactly-equal scores) the result is identical element-for-element
        # — and 3072-dim float32 cosine similarities effectively never tie, so
        # this is the branch real data takes. The only divergence is when an
        # *exact* tie block straddles the n-(k+1) partition boundary: which
        # tied id lands just inside vs. just outside the cut is tie-break
        # dependent, so the selected id subset may differ from full argsort.
        # The returned score multiset is unaffected. See
        # tests/test_embedding_topk.py for both halves of this contract.
        n = similarities.shape[0]
        want = k + 1  # include self; dropped after
        if want >= n:
            # Pool would be the whole array — partition buys nothing; sort all.
            top_indices = np.argsort(similarities)[::-1]
        else:
            # kth picks the (n-want)-th smallest as the partition boundary, so
            # the trailing `want` positions hold the largest `want` values
            # (unordered). Sort just those, descending, to recover full order.
            cand = np.argpartition(similarities, n - want)[-want:]
            cand = cand[np.argsort(similarities[cand])[::-1]]
            top_indices = cand
        results = []
        for i in top_indices:
            if self._ids[i] != card_id:
                results.append((self._ids[i], float(similarities[i])))
        return results[:k]

    def find_similar_batch(
        self, card_ids: list[str], k: int = 10
    ) -> dict[str, list[tuple[str, float]]]:
        """Top-k neighbours for many query cards in one matrix product.

        Equivalent to ``{cid: self.find_similar(cid, k) for cid in card_ids}``
        but computes a single ``(N x dim) @ (dim x M)`` matmul instead of M
        independent matvecs — the dominant cost of judge enrichment over a
        large store. Unknown ids (not in the store) map to ``[]``.

        Memory is ``N x M`` float32 (e.g. 10k x 100 ~= 4MB), safe for the
        batch sizes the pipeline produces.
        """
        # Unknown / empty: every requested id still gets a key (callers iterate
        # the input list and expect a result per id).
        result: dict[str, list[tuple[str, float]]] = {cid: [] for cid in card_ids}
        if self._embeddings is None:
            return result

        # Resolve query rows, dropping ids absent from the store. Preserve the
        # caller's order so the M columns line up with `present`.
        present = [cid for cid in card_ids if cid in self._id_set]
        if not present:
            return result
        q_idx = np.array([self._id_pos[cid] for cid in present])

        norms = self._get_norms()
        query_vecs = self._embeddings[q_idx]  # (M, dim)
        # ONE matmul over the whole matrix: (N, dim) @ (dim, M) -> (N, M).
        # Use np.matmul explicitly (not the @ operator, which dispatches to
        # ndarray.__matmul__) so the single-product invariant is observable.
        sims = np.matmul(self._embeddings, query_vecs.T)
        # Broadcast cosine denominator: column j divides by ||q_j||.
        denom = norms[:, None] * norms[q_idx][None, :] + _COSINE_EPS
        sims = sims / denom

        n = self._embeddings.shape[0]
        want = k + 1  # absorbs self, dropped below
        for col, cid in enumerate(present):
            col_sims = sims[:, col]
            if want >= n:
                order = np.argsort(col_sims)[::-1]
            else:
                cand = np.argpartition(col_sims, n - want)[-want:]
                order = cand[np.argsort(col_sims[cand])[::-1]]
            neighbours: list[tuple[str, float]] = []
            for i in order:
                other = self._ids[i]
                if other != cid:
                    neighbours.append((other, float(col_sims[i])))
            result[cid] = neighbours[:k]
        return result

    def has(self, card_id: str) -> bool:
        return card_id in self._id_set

    def count(self) -> int:
        return len(self._ids)

