"""Embedding storage and similarity search."""

from __future__ import annotations

import json
import logging
from pathlib import Path

import numpy as np

logger = logging.getLogger(__name__)
from openai import OpenAIError

EMBEDDING_MODEL = "gemini-embedding-2-preview"
EMBEDDING_DIM = 3072


class EmbeddingStore:
    """Numpy-based embedding storage with similarity search.

    Disk layout (per notebook ``nb``):
      * ``embeddings_{nb}.npy``         — float32 (N, dim) matrix
      * ``card_ids_{nb}.json``          — list[str] aligned with rows
      * ``embeddings_meta_{nb}.json``   — {"model", "dim", "created_at"}

    The meta sidecar guards against silently loading vectors generated by a
    different model or dim. When ``EMBEDDING_MODEL`` / ``EMBEDDING_DIM`` change
    in env, the old files are renamed ``*.legacy_{model}_{dim}`` and the
    store starts empty; pipeline backfill will re-embed on next run.
    """

    def __init__(
        self,
        embeddings_path: Path,
        ids_path: Path,
        llm,
        *,
        model: str = EMBEDDING_MODEL,
        dim: int = EMBEDDING_DIM,
    ) -> None:
        self.embeddings_path = embeddings_path
        self.ids_path = ids_path
        self.llm = llm
        self.model = model
        self.dim = dim
        self._embeddings: np.ndarray | None = None
        self._ids: list[str] = []
        self._id_set: set[str] = set()
        self._norms: np.ndarray | None = None  # cached L2 norms
        self._dirty: bool = False
        self._load()

    # ------------------------------------------------------------------
    # Meta sidecar (model/dim guard)
    # ------------------------------------------------------------------
    @property
    def _meta_path(self) -> Path:
        # `embeddings_{nb}.npy` -> `embeddings_meta_{nb}.json`. Falls back to
        # a generic name if the .npy stem doesn't start with "embeddings".
        stem = self.embeddings_path.stem  # e.g. "embeddings_default"
        if stem.startswith("embeddings_"):
            suffix = stem[len("embeddings_"):]
            name = f"embeddings_meta_{suffix}.json"
        elif stem == "embeddings":
            name = "embeddings_meta.json"
        else:
            name = f"{stem}_meta.json"
        return self.embeddings_path.with_name(name)

    def _read_meta(self) -> dict | None:
        try:
            return json.loads(self._meta_path.read_text())
        except (FileNotFoundError, json.JSONDecodeError):
            return None

    def _write_meta(self) -> None:
        from datetime import UTC, datetime
        self._meta_path.parent.mkdir(parents=True, exist_ok=True)
        payload = {
            "model": self.model,
            "dim": self.dim,
            "created_at": datetime.now(UTC).isoformat(),
        }
        tmp = self._meta_path.with_suffix(".json.tmp")
        tmp.write_text(json.dumps(payload))
        tmp.replace(self._meta_path)

    def _quarantine_stale(self, stale_model: str, stale_dim: int) -> None:
        """Rename .npy + ids.json to `.legacy_{model}_{dim}` so a future
        diff/recovery is possible. Failure to rename is non-fatal: we still
        proceed with an empty store."""
        suffix = f".legacy_{stale_model}_{stale_dim}"
        for path in (self.embeddings_path, self.ids_path):
            if path.exists():
                try:
                    path.rename(path.with_name(path.name + suffix))
                except OSError as e:
                    logger.warning(
                        "Failed to quarantine stale embedding file %s: %s",
                        path, e,
                    )

    def _load(self) -> None:
        """Load vectors + ids from disk, gated by sidecar match.

        Cases:
        * No .npy / no ids → fresh empty store (no sidecar written yet).
        * .npy + ids + matching sidecar → load as-is.
        * .npy + ids + no sidecar (legacy deployment) → assume current
          model/dim, load, and write the sidecar in-place (one-shot migration).
        * .npy + ids + sidecar mismatch → quarantine stale files, log warning,
          start empty. Pipeline backfill will re-embed on next run.
        """
        if not (self.embeddings_path.exists() and self.ids_path.exists()):
            return

        meta = self._read_meta()
        if meta is None:
            # Legacy: trust the on-disk files match the active model/dim,
            # and lock that in by writing the sidecar.
            vectors = np.load(self.embeddings_path)
            self._assert_shape_matches_dim(vectors)
            self._embeddings = vectors
            self._ids = json.loads(self.ids_path.read_text())
            self._id_set = set(self._ids)
            self._invalidate_norms()
            self._write_meta()
            return

        stale_model = meta.get("model")
        stale_dim = meta.get("dim")
        if stale_model == self.model and stale_dim == self.dim:
            vectors = np.load(self.embeddings_path)
            # Defence in depth: sidecar can lie (corruption / hand-edit /
            # half-finished migration). Reject on shape mismatch so the
            # error surfaces here, not later inside find_similar's cosine
            # math (silent corruption) or add_batch's vstack (cryptic).
            self._assert_shape_matches_dim(vectors)
            self._embeddings = vectors
            self._ids = json.loads(self.ids_path.read_text())
            self._id_set = set(self._ids)
            self._invalidate_norms()
            return

        logger.warning(
            "EmbeddingStore meta mismatch at %s: on-disk model=%r dim=%r, "
            "active model=%r dim=%r. Quarantining stale vectors and "
            "starting empty; re-embed will backfill on next pipeline run.",
            self.embeddings_path, stale_model, stale_dim,
            self.model, self.dim,
        )
        self._quarantine_stale(str(stale_model), int(stale_dim) if isinstance(stale_dim, int) else 0)
        # Sidecar must reflect active config now.
        self._write_meta()

    def _assert_shape_matches_dim(self, vectors: np.ndarray) -> None:
        """Guard against silent dim corruption at load time.

        Empty matrices (``shape[0] == 0``) are allowed: there is nothing
        to mis-interpret yet, and the next ``add_batch`` will populate
        with the active ``dim``. Anything populated must match ``self.dim``
        exactly — otherwise ``find_similar`` would silently compute cosine
        on stale vectors of a different dim (returns numbers, not crashes),
        which is the precise corruption window we are closing.
        """
        if vectors.ndim != 2:
            raise ValueError(
                f"embedding store shape invalid: ndim={vectors.ndim}, expected 2 "
                f"(file={self.embeddings_path})"
            )
        if vectors.shape[0] > 0 and vectors.shape[1] != self.dim:
            raise ValueError(
                f"embedding dim mismatch: loaded {vectors.shape[1]}, expected {self.dim} "
                f"(check EMBEDDING_DIM env or rebuild store at {self.embeddings_path})"
            )

    def _invalidate_norms(self) -> None:
        self._norms = None

    def _get_norms(self) -> np.ndarray:
        if self._norms is None and self._embeddings is not None:
            self._norms = np.linalg.norm(self._embeddings, axis=1)
        return self._norms

    def _save(self) -> None:
        self.embeddings_path.parent.mkdir(parents=True, exist_ok=True)
        if self._embeddings is not None:
            # np.save() auto-appends .npy if missing, so tmp must already end in .npy
            tmp_emb = self.embeddings_path.with_name(self.embeddings_path.stem + "_tmp.npy")
            np.save(tmp_emb, self._embeddings)
            tmp_emb.replace(self.embeddings_path)

        tmp_ids = self.ids_path.with_suffix(".json.tmp")
        tmp_ids.write_text(json.dumps(self._ids))
        tmp_ids.replace(self.ids_path)

        # Persist (or refresh) the model/dim sidecar alongside the vectors,
        # so a fresh store (no legacy files) still gets a guard on first save.
        if not self._meta_path.exists():
            self._write_meta()

    def _embed(self, texts: list[str]) -> np.ndarray:
        """Get embeddings for one or more texts via a single API call.

        Returns an (N, self.dim) float32 array.
        """
        import time
        for attempt in range(3):
            try:
                response = self.llm.embed("embed", input=texts, model=self.model)
                # response.data may not be sorted by index; sort to match input order.
                # Gemini's OpenAI-compat layer sometimes returns index=None for
                # the first element — coerce to 0 so sorting doesn't crash.
                sorted_data = sorted(response.data, key=lambda d: d.index if d.index is not None else 0)
                vecs = np.array([d.embedding for d in sorted_data], dtype=np.float32)
                if vecs.ndim >= 2 and vecs.shape[1] != self.dim:
                    raise ValueError(
                        f"Embedding dim mismatch: got {vecs.shape[1]}, expected {self.dim} "
                        f"(model={self.model!r}). Check EMBEDDING_DIM env var."
                    )
                return vecs
            except OpenAIError as e:
                if attempt < 2:
                    time.sleep(2 ** attempt)
                    continue
                logger.error("Embedding API error: %s", e)
                raise e

    def add(self, card_id: str, text: str) -> None:
        """Add embedding for a single card (delegates to add_batch)."""
        self.add_batch([(card_id, text)])

    def add_batch(self, items: list[tuple[str, str]]) -> None:
        """Add embeddings for multiple cards in a single API call.

        Items already present are silently skipped. Performs one API call,
        one np.vstack, and one disk save for the entire batch.
        """
        # Filter out already-embedded cards
        new_items = [(cid, text) for cid, text in items if cid not in self._id_set]
        if not new_items:
            return

        new_ids = [cid for cid, _ in new_items]
        new_texts = [text for _, text in new_items]

        vecs = self._embed(new_texts)  # single API call

        if self._embeddings is None:
            self._embeddings = vecs
        else:
            self._embeddings = np.vstack([self._embeddings, vecs])

        self._ids.extend(new_ids)
        self._id_set.update(new_ids)
        self._invalidate_norms()
        self._save()

    def update(self, card_id: str, text: str) -> None:
        """Update existing embedding.

        Only updates the in-memory vector and marks the store dirty.
        Call flush() to persist to disk (e.g. at end of request).
        """
        if card_id not in self._id_set:
            self.add(card_id, text)
            return

        idx = self._ids.index(card_id)
        vecs = self._embed([text])
        self._embeddings[idx] = vecs[0]
        self._invalidate_norms()
        self._dirty = True

    def flush(self) -> None:
        """Persist any dirty (deferred) writes to disk.

        No-op if the store has not been modified since last save.
        """
        if not self._dirty:
            return
        self._save()
        self._dirty = False

    def find_similar(self, card_id: str, k: int = 10) -> list[tuple[str, float]]:
        """Find k most similar cards (excluding self).

        Returns list of (card_id, similarity_score) sorted by similarity descending.
        """
        if self._embeddings is None or card_id not in self._id_set:
            return []

        idx = self._ids.index(card_id)
        query_vec = self._embeddings[idx]

        # Cosine similarity with cached norms
        norms = self._get_norms()
        query_norm = norms[idx]
        similarities = (self._embeddings @ query_vec) / (norms * query_norm + 1e-9)

        # Get top k+1 (including self), then filter
        top_indices = np.argsort(similarities)[::-1][: k + 1]
        results = []
        for i in top_indices:
            if self._ids[i] != card_id:
                results.append((self._ids[i], float(similarities[i])))
        return results[:k]

    def has(self, card_id: str) -> bool:
        return card_id in self._id_set

    def count(self) -> int:
        return len(self._ids)

