// Harness scenario taxonomy — mirrors the iOS Catalog addressing
// ({surface, scenario, appearance}) so parity capture URLs map 1:1 onto
// Catalog snapshot PNGs. Scenario ids correspond to
// ios/BooksAndVocab/Debug/Scenarios/BookshelfViewScenarios.swift.

export const SCENARIO_IDS = ['populated', 'single', 'empty'] as const
export type ScenarioId = (typeof SCENARIO_IDS)[number]

export const APPEARANCES = ['light', 'dark'] as const
export type Appearance = (typeof APPEARANCES)[number]

export interface HarnessConfig {
  scenario: ScenarioId
  appearance: Appearance
}

const DEFAULT_CONFIG: HarnessConfig = { scenario: 'populated', appearance: 'light' }

function pick<T extends string>(value: string | null, allowed: readonly T[], fallback: T): T {
  return value !== null && (allowed as readonly string[]).includes(value) ? (value as T) : fallback
}

/** Capture URLs are generated by the parity pipeline; unknown values fall back
 *  to the defaults instead of hard-failing so a bad URL still renders a frame
 *  (the parity diff will catch the mismatch). */
export function resolveHarnessConfig(search: string): HarnessConfig {
  const params = new URLSearchParams(search)
  return {
    scenario: pick(params.get('scenario'), SCENARIO_IDS, DEFAULT_CONFIG.scenario),
    appearance: pick(params.get('appearance'), APPEARANCES, DEFAULT_CONFIG.appearance),
  }
}
