// Harness scenario taxonomy — mirrors the iOS Catalog addressing
// ({surface, scenario, appearance}) so parity capture URLs map 1:1 onto
// Catalog snapshot PNGs. Scenario ids correspond to the iOS Debug scenario
// files (ios/BooksAndVocab/Debug/Scenarios/*Scenarios.swift)。

/** 每個 surface 自帶 scenario taxonomy；首位 = 該 surface 的預設 scenario。 */
export const SURFACE_SCENARIOS = {
  bookshelf: ['populated', 'single', 'empty'],
  settings: ['subscribed-active', 'logged-out', 'pricing-unavailable'],
  notebook: ['populated', 'single'],
  // Reader chrome（R1）+ Translation panel（R2）。chrome 6 態對齊
  // ReaderChromeScenarios.swift（paper 色帶在 fixture，與 light/dark 軸正交）；
  // translation 6 態對齊 ReaderScenarios.swift「Reader · Translation」（layout .fill =
  // scrim + bottom-sheet panel，無 reader 本體）。首位 reading-compact = 預設。
  reader: [
    'reading-compact',
    'reading-expanded',
    'loading-render',
    'loading-vocab',
    'reading-translation',
    'error-open-failed',
    'translation-expanded',
    'translation-collapsed',
    'translation-loading',
    'translation-error',
    'translation-explain-only',
    'translation-explanation-error',
  ],
  // Selection Toolbar — 對齊 SelectionToolbarScenarios.swift 3 態（vocab 多選
  // 底欄；selectionCount 0 全灰 disabled，>0 啟用 archive+delete）。首位
  // selection-multiple = 預設 scenario。
  'selection-toolbar': ['selection-multiple', 'selection-single', 'selection-none'],
  // Reader Selection Tile — 對齊 ReaderSelectionTileScenarios.swift 3 態
  // （chrome tile：selected mutedFill+primaryText / unselected pageBackground+
  // secondaryText / 並排對比）。首位 selection-pair = 預設 scenario。
  'selection-tile': ['selection-pair', 'selection-selected', 'selection-unselected'],
  vocabulary: ['populated', 'single', 'empty'],
} as const

export type SurfaceId = keyof typeof SURFACE_SCENARIOS
export type ScenarioId<S extends SurfaceId = SurfaceId> = (typeof SURFACE_SCENARIOS)[S][number]

export const APPEARANCES = ['light', 'dark'] as const
export type Appearance = (typeof APPEARANCES)[number]

/** Discriminated union（以 surface 鍵窄化）：路由端 switch(config.surface)
 *  後 scenario 自動收斂為該 surface 的合法 id。 */
export type HarnessConfig = {
  [S in SurfaceId]: { surface: S; scenario: ScenarioId<S>; appearance: Appearance }
}[SurfaceId]

/** 無 ?surface 參數時固定 bookshelf：第一刀的 capture URL（只有
 *  ?scenario/?appearance）必須持續解析到同一頁，parity manifest 不必回填。 */
const DEFAULT_SURFACE: SurfaceId = 'bookshelf'

function pick<T extends string>(value: string | null, allowed: readonly T[], fallback: T): T {
  return value !== null && (allowed as readonly string[]).includes(value) ? (value as T) : fallback
}

/** Capture URLs are generated by the parity pipeline; unknown values fall back
 *  to the defaults instead of hard-failing so a bad URL still renders a frame
 *  (the parity diff will catch the mismatch). Scenario 合法性以 surface 為界：
 *  跨 surface 的 scenario id 視同未知，落回該 surface 的預設。 */
export function resolveHarnessConfig(search: string): HarnessConfig {
  const params = new URLSearchParams(search)
  const surface = pick(params.get('surface'), Object.keys(SURFACE_SCENARIOS) as SurfaceId[], DEFAULT_SURFACE)
  const scenarios = SURFACE_SCENARIOS[surface]
  return {
    surface,
    scenario: pick(params.get('scenario'), scenarios, scenarios[0]),
    appearance: pick(params.get('appearance'), APPEARANCES, 'light'),
  } as HarnessConfig // surface 與 scenario 由同一 surface 取值，配對恆合法
}
