#!/usr/bin/env -S uv run python
"""Render audit/report.md from measured_values.json. One-shot. Pure stdlib."""
from __future__ import annotations
import json
from collections import Counter
from pathlib import Path

HERE = Path(__file__).parent
data = json.load(open(HERE / "measured_values.json"))
recs = data["records"]
clusters = data["clusters"]
meta = data["meta"]

clkind = {(c["prop_class"], c["literal"]): c["kind"] for c in clusters}


def prop_class(prop: str) -> str:
    if "padding" in prop:
        return "padding"
    if "margin" in prop:
        return "margin"
    if prop in ("gap", "row-gap", "column-gap", "grid-gap"):
        return "gap"
    if prop in ("width", "min-width", "max-width"):
        return "width"
    if prop in ("height", "min-height", "max-height"):
        return "height"
    if "radius" in prop:
        return "radius"
    if "font-size" in prop:
        return "font-size"
    if "line-height" in prop:
        return "line-height"
    if prop in ("top", "right", "bottom", "left", "inset"):
        return "offset"
    if "border" in prop:
        return "border"
    if "letter-spacing" in prop:
        return "tracking"
    return prop


rkind = Counter(clkind[(prop_class(r["prop"]), r["literal"])] for r in recs)
tot = len(recs)
pct = lambda n: f"{100 * n / tot:.1f}%"

l2 = [c for c in clusters if c["kind"] == "L2_candidate"]
orphans = [c for c in clusters if c["kind"] == "orphan"]
tokens = [c for c in clusters if c["kind"] == "token"]

lines: list[str] = []
w = lines.append

w("# iOS→Web Migration Engine — Delta Audit (v1)")
w("")
w("> Generated by `audit/extract.py` + `audit/report.py` over the hand-aligned web")
w("> surfaces. **Do not hand-edit** — re-run the scripts. Source = the 63-case")
w("> pixel-parity rewrite (`web/src/surfaces/*`, RMSE 0.016–0.135 vs iOS Catalog).")
w("")
w("## Scope")
w("")
w(f"- Targets: {len(meta['targets'])} CSS files")
for t in meta["targets"]:
    w(f"  - `{t}`")
w(f"- Token table (L1 SoT): `{meta['token_table']}`")
w(f"- **{tot}** hard-coded numeric literals extracted across **{len(clusters)}** value×prop-class clusters")
w("")
w("## Core numbers — overfit metric")
w("")
w("Every hard-coded literal is classified by how it can be *re-derived* by the engine:")
w("")
w("| class | meaning | records | % |")
w("|---|---|---:|---:|")
w(f"| **token** | literal == a `kg-tokens.css` scalar (pure L1 token→token) | {rkind['token']} | {pct(rkind['token'])} |")
w(f"| **L2_candidate** | non-token literal recurring in ≥2 surfaces → codifiable platform delta | {rkind['L2_candidate']} | {pct(rkind['L2_candidate'])} |")
w(f"| **orphan** | non-token literal in exactly 1 surface → suspected overfit | {rkind['orphan']} | {pct(rkind['orphan'])} |")
w("")
w(f"**Token-explicable: {pct(rkind['token'])}** · **L2-rule-explicable: {pct(rkind['L2_candidate'])}** · "
  f"**orphan / overfit: {pct(rkind['orphan'])}**")
w("")
w("Interpretation: ~70% of all measured geometry is already a pure token lookup the")
w("engine gets for free (L1). ~18% recurs across surfaces — these are the systematic")
w("platform deltas worth codifying as L2 law. The remaining ~12% are single-surface")
w("orphans: either genuine page-specific anchors (a nav title's measured top) or")
w("overfit residue. **Orphan % is the engine's overfit budget** — the L3 holdout loop")
w("must keep it from leaking into the codex.")
w("")
w(f"Cluster-level: {len(tokens)} token clusters, {len(l2)} L2 clusters, {len(orphans)} orphan clusters.")
w("")
w("## Top L2-rule clusters (recurring non-token deltas, by surface spread)")
w("")
w("| literal | prop-class | occ | surfaces | measured? | spread |")
w("|---|---|---:|---:|:---:|---|")
for c in l2:
    m = "✓" if c["any_measured"] else ""
    sp = ", ".join(s.replace("shared:", "") for s in c["surfaces"])
    w(f"| `{c['literal']}` | {c['prop_class']} | {c['n_occurrences']} | {c['n_surfaces']} | {m} | {sp} |")
w("")
w("## Orphan clusters (single-surface — overfit candidates / page anchors)")
w("")
w("These do **not** enter the codex. Each is either a legitimately page-specific")
w("anchor (kept in the surface CSS) or a residue the L3 loop should re-derive.")
w("")
w("| literal | prop-class | surface | selector | comment |")
w("|---|---|---|---|---|")
for c in sorted(orphans, key=lambda c: -c["n_occurrences"])[:30]:
    p = c["provenance"][0]
    cm = (p["comment"][:70] + "…") if len(p["comment"]) > 70 else p["comment"]
    w(f"| `{c['literal']}` | {c['prop_class']} | {p['file'].split('/')[-2] if '/' in p['file'] else p['file']} | `{p['selector'][:30]}` | {cm} |")
if len(orphans) > 30:
    w(f"| … | | | | _({len(orphans) - 30} more orphans in JSON)_ |")
w("")
w("## Method notes")
w("")
w("- Token classification resolves `var()` aliases one hop through the token table,")
w("  then matches the literal px/unitless scalar. `em`/`rem`/`%` excluded (relative,")
w("  not pixel deltas). `opacity`/`z-index`/`flex` skipped (structural primitives).")
w("- A cluster keys on (normalized prop-class, literal). `font-weight: 700/600/400`")
w("  cluster widely because ElmsSans ships 400/700 only and Songti has no usable Bold")
w("  face on Chromium — the canonical typographic platform delta (L2).")
w("- `measured?` = the nearest comment block contains the literal string `measured`,")
w("  the convention the parity author used to flag a value derived from pixel diffing")
w("  rather than a token. These are the highest-confidence L2 inputs.")
w("")

(HERE / "report.md").write_text("\n".join(lines) + "\n")
print(f"wrote report.md ({len(lines)} lines)")
