#!/usr/bin/env python3
"""gen_web_tokens — render the cross-platform design tokens into web CSS.

SoT = design-system/tokens.json (itself a verified mirror of the iOS Swift
token files; see ops/token_drift_check.py). This script is the ONE place that
turns those tokens into CSS custom properties for every web surface.

Outputs (GENERATED — never hand-edit):
  design-system/dist/kg-tokens.css         canonical, link this from any web page
  chrome-extension/shared/tokens.css       bundled copy for the extension
  chrome-extension/shared/kg-components.css bundled copy of the hand-authored
                                           primitives for the extension surfaces
  backend/static/kg-tokens.css             bundled copy for the public 官網 (served
                                           by FastAPI StaticFiles; rsync ships only
                                           backend/, so the copy must live here)
  backend/static/kg-components.css         bundled copy of the same primitives for
                                           the public 官網

The component primitives (design-system/dist/kg-components.css) are HAND-AUTHORED;
that dist/ file is their source. They are copied verbatim into BOTH the extension
and backend/static/ so every web surface consumes ONE component vocabulary that
tracks the iOS app. (Earlier the extension was excluded for fear its .kg-btn /
.kg-card class names would collide. Invariant that makes bundling safe: the base
primitive classes — .kg-btn / .kg-card / .kg-chip — are owned SOLELY by this file;
each surface's own CSS only defines BEM-scoped LAYOUT classes (.kg-list-card /
.kg-popup__btn / .kg-section-card) that compose with the primitives, and the
markup opts in explicitly. Any surface redefining a base class is a bug.)

Selector strategy (shadow-DOM safe):
  Invariant tokens  ->  `:root, :host`
  Light / default   ->  `:root, :host, [data-theme="light"]`
  Dark              ->  `[data-theme="dark"]`
  Sepia             ->  `[data-theme="sepia"]`
`:host` lets the extension content script inject tokens.css into a closed shadow
root and have the variables actually apply inside the popup (a `:root`-only
sheet silently fails in shadow scope).

Modes:
  (default)  write all outputs
  --check    render in-memory, diff against on-disk; exit 1 if stale (CI gate)

Run:  uv run python ops/gen_web_tokens.py
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
TOKENS_JSON = REPO / "design-system" / "tokens.json"
DIST_TOKENS = REPO / "design-system" / "dist" / "kg-tokens.css"
DIST_COMPONENTS = REPO / "design-system" / "dist" / "kg-components.css"
EXT_TOKENS = REPO / "chrome-extension" / "shared" / "tokens.css"
EXT_COMPONENTS = REPO / "chrome-extension" / "shared" / "kg-components.css"
BACKEND_STATIC = REPO / "backend" / "static"
BACKEND_TOKENS = BACKEND_STATIC / "kg-tokens.css"
BACKEND_COMPONENTS = BACKEND_STATIC / "kg-components.css"

HEADER = (
    "/* ============================================================\n"
    "   GENERATED by ops/gen_web_tokens.py from design-system/tokens.json\n"
    "   DO NOT EDIT — change tokens.json and re-run the generator.\n"
    "   SoT: ios/BooksBrowser/Models/AppColors|AppTheme|AppMetrics|AppFonts.swift\n"
    "   Drift from iOS is guarded by ops/token_drift_check.py.\n"
    "   ============================================================ */\n\n"
)

# easeOutCubic: no-overshoot safe approximation of an underdamped spring's settle.
# Shared by every motion.spring token (duration = response). See motion.$comment-spring.
SPRING_EASE = "cubic-bezier(0.33, 1, 0.68, 1)"

# Legacy spacing aliases so existing feature CSS keeps working while it migrates
# to the canonical iOS-numeric --sp-N scale. key -> canonical scale key.
SPACE_ALIASES = {
    "xs": "1", "sm": "2", "compact": "3", "md": "4",
    "lg": "6", "xl": "7", "xxl": "9",
}


# --------------------------------------------------------------------------
# Color resolution
# --------------------------------------------------------------------------

def _hex(rgb: list[float]) -> str:
    return "#" + "".join(f"{round(c * 255):02X}" for c in rgb)


def _rgba(rgb: list[float], alpha: float) -> str:
    r, g, b = (round(c * 255) for c in rgb)
    a = f"{alpha:g}"
    return f"rgba({r}, {g}, {b}, {a})"


def _primitive_rgb(tokens: dict, ref: str) -> list[float]:
    """Resolve 'accent.light' / 'on-brand-hero.any' to its rgb floats."""
    name, variant = ref.rsplit(".", 1)
    return tokens["color"]["primitive"][name][variant]["rgb"]


def resolve_color(tokens: dict, spec: dict) -> str:
    """Resolve one theme-palette color spec to a CSS color string."""
    if "css" in spec:
        if spec["css"] == "":
            raise ValueError(f"empty css color value in spec: {spec}")
        return spec["css"]
    if "rgb" in spec:
        return _hex(spec["rgb"])
    if "ref" in spec:
        rgb = _primitive_rgb(tokens, spec["ref"])
        if "alpha" in spec:
            return _rgba(rgb, spec["alpha"])
        return _hex(rgb)
    if "overlay" in spec:
        base = [0.0, 0.0, 0.0] if spec["overlay"] == "black" else [1.0, 1.0, 1.0]
        return _rgba(base, spec["alpha"])
    if "overlay-rgb" in spec:
        return _rgba(spec["overlay-rgb"], spec["alpha"])
    raise ValueError(f"un-resolvable color spec: {spec}")


# --------------------------------------------------------------------------
# Rendering
# --------------------------------------------------------------------------

def _emit_block(selector: str, decls: list[tuple[str, str]]) -> str:
    # Guard against blanked/typo'd tokens.json keys emitting malformed `--x: ;`
    # declarations that would still pass --check (it only diffs render-vs-disk).
    for name, value in decls:
        if value == "":
            raise ValueError(f"empty CSS value for {name} (blank/missing tokens.json source)")
    body = "".join(f"  {name}: {value};\n" for name, value in decls)
    return f"{selector} {{\n{body}}}\n\n"


def _invariant_decls(tokens: dict) -> list[tuple[str, str]]:
    d: list[tuple[str, str]] = []

    fam = tokens["type"]["family"]
    for key in ("serif", "sans", "italic", "mono"):
        d.append((f"--font-{key}", fam[key]))

    for key, spec in tokens["type"]["scale"].items():
        if key.startswith("$"):
            continue
        d.append((f"--text-{key}", f"{spec['px']:g}px"))

    for key, spec in tokens["type"]["tracking"].items():
        if key.startswith("$"):
            continue
        d.append((f"--tracking-{key}", f"{spec['px']:g}px"))

    for key, spec in tokens["type"]["leading"].items():
        if key.startswith("$"):
            continue
        d.append((f"--leading-{key}", f"{spec['ratio']:g}"))

    scale = tokens["space"]["scale"]
    for key, spec in scale.items():
        if key.startswith("$"):
            continue
        d.append((f"--sp-{key}", f"{spec['px']:g}px"))
    # back-compat semantic aliases
    for alias, target in SPACE_ALIASES.items():
        d.append((f"--sp-{alias}", f"var(--sp-{target})"))
    for key, spec in tokens["space"]["semantic"].items():
        if key.startswith("$"):
            continue
        d.append((f"--{key}", f"{spec['px']:g}px"))

    rscale = tokens["radius"]["scale"]
    for key, spec in rscale.items():
        if key.startswith("$"):
            continue
        d.append((f"--radius-{key}", f"{spec['px']:g}px"))
    for key, spec in tokens["radius"]["semantic"].items():
        if key.startswith("$"):
            continue
        px = rscale[spec["ref"]]["px"]
        d.append((f"--radius-{key}", f"{px:g}px"))

    mo = tokens["motion"]
    for key, spec in mo["duration"].items():
        if key.startswith("$"):
            continue
        d.append((f"--dur-{key}", f"{spec['s']:g}s"))
    for key, spec in mo["easing"].items():
        if key.startswith("$"):
            continue
        d.append((f"--ease-{key}", spec["css"]))
    # spring physics → `<response>s <easeOutCubic>` no-overshoot safe approximation.
    # damping is $swift-guarded in tokens.json but NOT expressible in cubic-bezier (overshoot
    # dropped for safety); see motion.$comment-spring.
    for key, spec in mo.get("spring", {}).items():
        if key.startswith("$"):
            continue
        d.append((f"--spring-{key}", f"{spec['response']:g}s {SPRING_EASE}"))
    # composed "duration easing" pairs for `transition: <prop> var(--motion-X)`.
    # quick/control/chip from timing-curve duration+easing; standard/emphasized from spring.
    for key in ("quick", "control", "chip"):
        ease = mo["easing"].get(key, {}).get("css", "ease-out")
        d.append((f"--motion-{key}", f"{mo['duration'][key]['s']:g}s {ease}"))
    for key in ("standard", "emphasized"):
        d.append((f"--motion-{key}", f"{mo['spring'][key]['response']:g}s {SPRING_EASE}"))
    for key, css in mo.get("transition", {}).items():
        if key.startswith("$"):
            continue
        d.append((f"--transition-{key}", css))
    tap = mo["tap-feedback"]
    d.append(("--press-scale", f"{tap['scale-down']['value']:g}"))
    d.append(("--press-opacity", f"{tap['opacity-dip']['value']:g}"))

    return d


def _elevation_decls(tokens: dict, dark: bool) -> list[tuple[str, str]]:
    d: list[tuple[str, str]] = []
    boost = tokens["elevation"]["dark-boost"] if dark else 1.0
    for key, step in tokens["elevation"]["steps"].items():
        if key.startswith("$"):
            continue
        if step["opacity"] == 0:
            d.append((f"--elevation-{key}", "none"))
        else:
            op = round(step["opacity"] * boost, 4)
            d.append((
                f"--elevation-{key}",
                f"0 {step['y']:g}px {step['blur']:g}px rgba(0, 0, 0, {op:g})",
            ))
    return d


def _theme_decls(tokens: dict, theme: str) -> list[tuple[str, str]]:
    d: list[tuple[str, str]] = []
    for key, spec in tokens["color"]["theme"][theme].items():
        if key.startswith("$"):
            continue
        d.append((f"--{key}", resolve_color(tokens, spec)))
    vh = tokens["color"]["vocab-highlight"].get(theme)
    if vh:
        d.append(("--vocab-highlight", vh["css"]))
    d += _elevation_decls(tokens, dark=(theme == "dark"))
    return d


def render_tokens_css(tokens: dict) -> str:
    out = [HEADER]
    out.append(_emit_block(
        ":root, :host",
        _invariant_decls(tokens),
    ).replace("{\n", "{\n  /* --- theme-invariant: typography / space / radius / motion --- */\n", 1))
    out.append(_emit_block(":root, :host, [data-theme=\"light\"]", _theme_decls(tokens, "light")))
    out.append(_emit_block("[data-theme=\"dark\"]", _theme_decls(tokens, "dark")))
    out.append(_emit_block("[data-theme=\"sepia\"]", _theme_decls(tokens, "sepia")))
    # reduced-motion: web equivalent of iOS accessibilityReduceMotion.
    # Collapse every composed timing var (dur/spring/motion) to a near-zero duration
    # so `transition: x var(--spring-press)` / `var(--motion-standard)` also honor RM.
    mo = tokens["motion"]
    rm_vars = [f"--dur-{k}" for k in mo["duration"] if not k.startswith("$")]
    rm_vars += [f"--spring-{k}" for k in mo["spring"] if not k.startswith("$")]
    rm_vars += ["--motion-quick", "--motion-control", "--motion-chip",
                "--motion-standard", "--motion-emphasized"]
    rm_body = "".join(f"    {v}: 0.01ms;\n" for v in rm_vars)
    out.append(
        "@media (prefers-reduced-motion: reduce) {\n"
        "  :root, :host {\n"
        f"{rm_body}"
        "  }\n}\n"
    )
    return "".join(out)


# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------

def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description="Render design tokens into web CSS.")
    ap.add_argument("--check", action="store_true",
                    help="verify on-disk outputs are up to date; exit 1 if stale")
    args = ap.parse_args()

    tokens = json.loads(TOKENS_JSON.read_text(encoding="utf-8"))
    tokens_css = render_tokens_css(tokens)
    # The component primitives are hand-authored; dist/ is their source. We copy
    # that source verbatim into the backend bundle so the deployed 官網 is
    # self-contained (rsync ships only backend/). --check then guards the copy.
    components_css = DIST_COMPONENTS.read_text(encoding="utf-8")

    targets: list[tuple[Path, str]] = [
        (DIST_TOKENS, tokens_css),
        (EXT_TOKENS, tokens_css),
        (EXT_COMPONENTS, components_css),
        (BACKEND_TOKENS, tokens_css),
        (BACKEND_COMPONENTS, components_css),
    ]

    if args.check:
        stale = [p for p, c in targets if not p.exists() or p.read_text(encoding="utf-8") != c]
        if stale:
            print("STALE web token outputs (run: uv run python ops/gen_web_tokens.py):")
            for p in stale:
                print(f"  - {p.relative_to(REPO)}")
            return 1
        print("web token outputs are up to date.")
        return 0

    for p, c in targets:
        _write(p, c)
        print(f"wrote {p.relative_to(REPO)} ({len(c)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
