#!/usr/bin/env -S uv run --python 3.13 python
"""gen_web_components — render cross-platform component specs into web CSS + JS.

SoT = design-system/components.json (hand-authored component structure).
Consumes design-system/tokens.json for material (colors, fonts, spacing) but
only by REFERENCE — token values are emitted as var(--*) references, not
hard-coded, so token changes auto-propagate without re-running this script.

Outputs (GENERATED — never hand-edit):
  design-system/dist/kg-components.css    canonical component CSS
  chrome-extension/shared/kg-components.css bundled copy
  backend/static/kg-components.css        bundled copy for 官網
  design-system/dist/review-gradient.js   canonical JS algorithm
  chrome-extension/shared/review-gradient.js bundled copy

Run:  uv run python ops/gen_web_components.py
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
COMPONENTS_JSON = REPO / "design-system" / "components.json"
# Component STRUCTURES (generated from components.json) — separate from
# kg-components.css (hand-authored primitives) so both can coexist.
DIST_STRUCTURES = REPO / "design-system" / "dist" / "kg-component-structures.css"
DIST_REVIEW_GRADIENT = REPO / "design-system" / "dist" / "review-gradient.js"
EXT_STRUCTURES = REPO / "chrome-extension" / "shared" / "kg-component-structures.css"
EXT_REVIEW_GRADIENT = REPO / "chrome-extension" / "shared" / "review-gradient.js"
BACKEND_STATIC = REPO / "backend" / "static"
BACKEND_STRUCTURES = BACKEND_STATIC / "kg-component-structures.css"
BACKEND_REVIEW_GRADIENT = BACKEND_STATIC / "review-gradient.js"

CSS_HEADER = (
    "/* ============================================================\n"
    "   GENERATED by ops/gen_web_components.py from design-system/components.json\n"
    "   DO NOT EDIT — change components.json and re-run the generator.\n"
    "   SoT: ios/BooksAndVocab/Views/Vocabulary/Components/WordRow.swift,\n"
    "        ios/BooksAndVocab/Views/Vocabulary/Scenes/KGVocabPresenter.swift,\n"
    "        ios/BooksAndVocab/Models/ReviewGradient.swift\n"
    "   ============================================================ */\n\n"
)

JS_HEADER = (
    "/* ============================================================\n"
    "   GENERATED by ops/gen_web_components.py from design-system/components.json\n"
    "   DO NOT EDIT — change components.json and re-run the generator.\n"
    "   SoT: ios/BooksAndVocab/Models/ReviewGradient.swift\n"
    "   ============================================================ */\n\n"
)


def _render_css_value(value: dict | str) -> str:
    """Resolve a component property value to a CSS string."""
    if isinstance(value, str):
        return value
    if "var" in value:
        return f"var({value['var']})"
    if "expr" in value:
        return value["expr"]
    raise ValueError(f"un-resolvable CSS value: {value}")


def _emit_css_rule(selector: str, props: dict) -> str:
    """Emit a single CSS rule block."""
    lines = [f"{selector} {{"]
    for prop_name, prop_value in props.items():
        css_name = prop_name[0].lower() + prop_name[1:]
        css_name = "".join(
            "-" + c.lower() if c.isupper() else c for c in css_name
        ).lstrip("-")
        lines.append(f"  {css_name}: {_render_css_value(prop_value)};")
    lines.append("}")
    return "\n".join(lines)


def _emit_states(base_selector: str, states: dict) -> list[str]:
    """Emit CSS state pseudo-class rules (:hover, :active)."""
    blocks = []
    for state_name, props in states.items():
        selector = f"{base_selector}:{state_name}"
        blocks.append(_emit_css_rule(selector, props))
    return blocks


def _emit_modifiers(base_selector: str, modifiers: dict) -> list[str]:
    """Emit CSS modifier-class rules (.class--active) — BEM modifiers for variants
    that are toggled by markup (e.g. a selected chip), not by pseudo-state."""
    blocks = []
    for mod_name, props in modifiers.items():
        blocks.append(_emit_css_rule(f"{base_selector}--{mod_name}", props))
    return blocks


def _walk_component(name: str, spec: dict, out: list[str]) -> None:
    """Recursively walk a component spec and emit CSS rules."""
    css_spec = spec.get("css")
    if not css_spec:
        return

    class_name = css_spec["className"]
    props = css_spec.get("properties", {})
    out.append(_emit_css_rule(f".{class_name}", props))

    # State pseudo-classes
    states = css_spec.get("states", {})
    if states:
        out.extend(_emit_states(f".{class_name}", states))

    # Modifier classes (markup-toggled variants, e.g. --active)
    modifiers = css_spec.get("modifiers", {})
    if modifiers:
        out.extend(_emit_modifiers(f".{class_name}", modifiers))

    # Children
    children = spec.get("children", {})
    for child_name, child_spec in children.items():
        _walk_component(child_name, child_spec, out)


def render_components_css(components: dict) -> str:
    """Render components.json into CSS."""
    out = [CSS_HEADER]

    for comp_name, comp_spec in components.get("components", {}).items():
        _walk_component(comp_name, comp_spec, out)
        out.append("")

    return "\n".join(out)


def render_review_gradient_js(algo: dict) -> str:
    """Render ReviewGradient algorithm into standalone JS module."""
    stops = algo["stops"]
    stops_json = json.dumps(stops, indent=2)

    return JS_HEADER + f""""use strict";

/**
 * ReviewGradient — mirrors iOS ReviewGradient.swift
 * HSL-interpolated review-progress color.
 * ratio 0 = fresh green → 1 = due yellow → 2 = overdue red → 3 = deep purple
 */

const REVIEW_STOPS = {stops_json};

function _interpolateHSL(ratio) {{
  const clamped = Math.max(0, ratio);
  const first = REVIEW_STOPS[0];
  const last = REVIEW_STOPS[REVIEW_STOPS.length - 1];
  if (clamped <= first.at) return first;
  if (clamped >= last.at) return last;

  for (let i = 0; i < REVIEW_STOPS.length - 1; i++) {{
    const s0 = REVIEW_STOPS[i];
    const s1 = REVIEW_STOPS[i + 1];
    if (clamped <= s1.at) {{
      const t = (clamped - s0.at) / (s1.at - s0.at);
      let dh = s1.h - s0.h;
      if (dh > 180) dh -= 360;
      if (dh < -180) dh += 360;
      const h = ((s0.h + dh * t) % 360 + 360) % 360;
      return {{ h, s: s0.s + (s1.s - s0.s) * t, l: s0.l + (s1.l - s0.l) * t }};
    }}
  }}
  return last;
}}

function _hslToRGB(h, s, l) {{
  const c = (1 - Math.abs(2 * l - 1)) * s;
  const x = c * (1 - Math.abs(((h / 60) % 2) - 1));
  const m = l - c / 2;
  let r1, g1, b1;
  if (h < 60)       [r1, g1, b1] = [c, x, 0];
  else if (h < 120) [r1, g1, b1] = [x, c, 0];
  else if (h < 180) [r1, g1, b1] = [0, c, x];
  else if (h < 240) [r1, g1, b1] = [0, x, c];
  else if (h < 300) [r1, g1, b1] = [x, 0, c];
  else              [r1, g1, b1] = [c, 0, x];
  return {{
    r: Math.round((r1 + m) * 255),
    g: Math.round((g1 + m) * 255),
    b: Math.round((b1 + m) * 255),
  }};
}}

/**
 * Get the review-progress color for a given ratio.
 * @param {{number}} ratio — 0=fresh, 1=due, 2=overdue, 3=deep overdue
 * @returns {{string}} CSS rgb() color
 */
function reviewGradientColor(ratio) {{
  const hsl = _interpolateHSL(ratio);
  const rgb = _hslToRGB(hsl.h, hsl.s / 100, hsl.l / 100);
  return `rgb(${{rgb.r}}, ${{rgb.g}}, ${{rgb.b}})`;
}}

/* eslint-disable no-unused-vars */
// UMD-style export: works as browser global, CommonJS, or ES module
if (typeof module !== "undefined" && module.exports) {{
  module.exports = {{ reviewGradientColor, REVIEW_STOPS }};
}} else if (typeof window !== "undefined") {{
  window.KGReviewGradient = {{ reviewGradientColor, REVIEW_STOPS }};
}}
"""


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description="Render component specs into web CSS + JS.")
    ap.add_argument("--check", action="store_true",
                    help="verify on-disk outputs are up to date; exit 1 if stale")
    args = ap.parse_args()

    components = json.loads(COMPONENTS_JSON.read_text(encoding="utf-8"))

    css = render_components_css(components)
    js = render_review_gradient_js(components["algorithms"]["ReviewGradient"])

    targets: list[tuple[Path, str]] = [
        (DIST_STRUCTURES, css),
        (EXT_STRUCTURES, css),
        (BACKEND_STRUCTURES, css),
        (DIST_REVIEW_GRADIENT, js),
        (EXT_REVIEW_GRADIENT, js),
        (BACKEND_REVIEW_GRADIENT, js),
    ]

    if args.check:
        stale = [p for p, c in targets if not p.exists() or p.read_text(encoding="utf-8") != c]
        if stale:
            print("STALE web component outputs (run: uv run python ops/gen_web_components.py):")
            for p in stale:
                print(f"  - {p.relative_to(REPO)}")
            return 1
        print("web component outputs are up to date.")
        return 0

    for p, c in targets:
        _write(p, c)
        print(f"wrote {p.relative_to(REPO)} ({len(c)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
