#!/usr/bin/env -S uv run --python 3.13 python
"""gen_web_tokens — render the cross-platform design tokens into web CSS.

SoT = design-system/tokens.json (W3C DTCG format). This script is the ONE place
that turns those tokens into CSS custom properties for every web surface.

Outputs (GENERATED — never hand-edit):
  design-system/dist/kg-tokens.css         canonical
  backend/static/kg-tokens.css             bundled copy for the public 官網
  backend/static/kg-components.css         bundled copy of the same primitives

Modes:
  (default)  write all outputs
  --check    render in-memory, diff against on-disk; exit 1 if stale (CI gate)

Run:  uv run python ops/gen_web_tokens.py
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
TOKENS_JSON = REPO / "design-system" / "tokens.json"
DIST_TOKENS = REPO / "design-system" / "dist" / "kg-tokens.css"
DIST_COMPONENTS = REPO / "design-system" / "dist" / "kg-components.css"
BACKEND_STATIC = REPO / "backend" / "static"
BACKEND_TOKENS = BACKEND_STATIC / "kg-tokens.css"
BACKEND_COMPONENTS = BACKEND_STATIC / "kg-components.css"

HEADER = (
    "/* ============================================================\n"
    "   GENERATED by ops/gen_web_tokens.py from design-system/tokens.json\n"
    "   DO NOT EDIT — change tokens.json and re-run the generator.\n"
    "   SoT: ios/BooksAndVocab/Models/AppColors|AppTheme|AppMetrics|AppFonts.swift\n"
    "   Drift from iOS is guarded by ops/token_drift_check.py.\n"
    "   ============================================================ */\n\n"
)

SPRING_EASE = "cubic-bezier(0.33, 1, 0.68, 1)"

SPACE_ALIASES = {
    "xs": "1", "sm": "2", "compact": "3", "md": "4",
    "lg": "6", "xl": "7", "xxl": "9",
}

_REF_RE = re.compile(r"^\{([\w\-\.]+)\}$")


def _resolve(spec: dict, tokens: dict) -> str | float | int:
    """Resolve a DTCG token value, expanding {path} references recursively."""
    raw = spec["$value"]
    if not isinstance(raw, str):
        return raw
    m = _REF_RE.match(raw)
    if not m:
        return raw
    path = m.group(1).split(".")
    node = tokens
    for part in path:
        node = node[part]
    return _resolve(node, tokens)


def _num(spec: dict, tokens: dict) -> float:
    """Resolve a token to a numeric value."""
    v = _resolve(spec, tokens)
    if isinstance(v, (int, float)):
        return float(v)
    # Strip common CSS units
    s = str(v)
    for suffix in ("px", "s", "ms"):
        if s.endswith(suffix):
            return float(s[:-len(suffix)])
    return float(s)


def _skip_meta(items):
    """Yield (key, value) pairs skipping metadata keys."""
    for k, v in items:
        if k.startswith("$"):
            continue
        yield k, v


def _emit_block(selector: str, decls: list[tuple[str, str]]) -> str:
    for name, value in decls:
        if value == "":
            raise ValueError(f"empty CSS value for {name}")
    body = "".join(f"  {name}: {value};\n" for name, value in decls)
    return f"{selector} {{\n{body}}}\n\n"


def _invariant_decls(tokens: dict) -> list[tuple[str, str]]:
    d: list[tuple[str, str]] = []

    fam = tokens["type"]["family"]
    for key, spec in _skip_meta(fam.items()):
        d.append((f"--font-{key}", str(_resolve(spec, tokens))))

    for key, spec in _skip_meta(tokens["type"]["scale"].items()):
        d.append((f"--text-{key}", str(_resolve(spec, tokens))))

    for key, spec in _skip_meta(tokens["type"]["tracking"].items()):
        d.append((f"--tracking-{key}", str(_resolve(spec, tokens))))

    for key, spec in _skip_meta(tokens["type"]["leading"].items()):
        d.append((f"--leading-{key}", str(_resolve(spec, tokens))))

    scale = tokens["space"]["scale"]
    for key, spec in _skip_meta(scale.items()):
        d.append((f"--sp-{key}", str(_resolve(spec, tokens))))
    for alias, target in SPACE_ALIASES.items():
        d.append((f"--sp-{alias}", f"var(--sp-{target})"))
    for key, spec in _skip_meta(tokens["space"]["semantic"].items()):
        d.append((f"--{key}", str(_resolve(spec, tokens))))

    rscale = tokens["radius"]["scale"]
    for key, spec in _skip_meta(rscale.items()):
        d.append((f"--radius-{key}", str(_resolve(spec, tokens))))
    for key, spec in _skip_meta(tokens["radius"]["semantic"].items()):
        d.append((f"--radius-{key}", str(_resolve(spec, tokens))))

    mo = tokens["motion"]
    for key, spec in _skip_meta(mo["duration"].items()):
        d.append((f"--dur-{key}", str(_resolve(spec, tokens))))
    for key, spec in _skip_meta(mo["easing"].items()):
        d.append((f"--ease-{key}", str(_resolve(spec, tokens))))
    for key, spec in _skip_meta(mo.get("spring", {}).items()):
        resp = _num(spec["response"], tokens)
        d.append((f"--spring-{key}", f"{resp:g}s {SPRING_EASE}"))
    for key in ("quick", "control", "chip"):
        dur = str(_resolve(mo["duration"][key], tokens))
        ease = str(_resolve(mo["easing"][key], tokens))
        d.append((f"--motion-{key}", f"{dur} {ease}"))
    for key in ("standard", "emphasized"):
        resp = _num(mo["spring"][key]["response"], tokens)
        d.append((f"--motion-{key}", f"{resp:g}s {SPRING_EASE}"))
    for key, spec in _skip_meta(mo.get("transition", {}).items()):
        d.append((f"--transition-{key}", str(_resolve(spec, tokens))))
    tap = mo["tap-feedback"]
    d.append(("--press-scale", str(_resolve(tap["scale-down"], tokens))))
    d.append(("--press-opacity", str(_resolve(tap["opacity-dip"], tokens))))

    for key, spec in _skip_meta(tokens.get("web-only", {}).get("invariant-color", {}).items()):
        d.append((f"--{key}", str(_resolve(spec, tokens))))

    tp = tokens.get("web-only", {}).get("theme-preview")
    if tp:
        src = str(_resolve(tp["swatch-of"], tokens))
        for theme in tp["themes"]:
            spec = tokens["color"]["theme"][theme][src]
            d.append((f"--swatch-{theme}", str(_resolve(spec, tokens))))

    for key, spec in _skip_meta(tokens.get("web-only", {}).get("invariant-value", {}).items()):
        d.append((f"--{key}", str(_resolve(spec, tokens))))

    return d


def _elevation_decls(tokens: dict, dark: bool) -> list[tuple[str, str]]:
    d: list[tuple[str, str]] = []
    boost = _num(tokens["elevation"]["dark-boost"], tokens) if dark else 1.0
    for key, step in _skip_meta(tokens["elevation"]["steps"].items()):
        op = _num(step["opacity"], tokens)
        if op == 0:
            d.append((f"--elevation-{key}", "none"))
        else:
            op = round(op * boost, 4)
            blur = _num(step["blur"], tokens)
            y = _num(step["y"], tokens)
            d.append((f"--elevation-{key}", f"0 {y:g}px {blur:g}px rgba(0, 0, 0, {op:g})"))
    return d


def _theme_decls(tokens: dict, theme: str) -> list[tuple[str, str]]:
    d: list[tuple[str, str]] = []
    for key, spec in _skip_meta(tokens["color"]["theme"][theme].items()):
        d.append((f"--{key}", str(_resolve(spec, tokens))))
    vh = tokens["color"]["vocab-highlight"].get(theme)
    if vh:
        d.append(("--vocab-highlight", str(_resolve(vh, tokens))))
    for key, spec in _skip_meta(tokens.get("web-only", {}).get("theme-color", {}).items()):
        d.append((f"--{key}", str(_resolve(spec[theme], tokens))))
    d += _elevation_decls(tokens, dark=(theme == "dark"))
    return d


def render_tokens_css(tokens: dict) -> str:
    out = [HEADER]
    out.append(_emit_block(
        ":root, :host",
        _invariant_decls(tokens),
    ).replace("{\n", "{\n  /* --- theme-invariant: typography / space / radius / motion --- */\n", 1))
    out.append(_emit_block(":root, :host, [data-theme=\"light\"]", _theme_decls(tokens, "light")))
    out.append(_emit_block("[data-theme=\"dark\"]", _theme_decls(tokens, "dark")))
    out.append(_emit_block("[data-theme=\"sepia\"]", _theme_decls(tokens, "sepia")))
    mo = tokens["motion"]
    rm_vars = [f"--dur-{k}" for k, _ in _skip_meta(mo["duration"].items())]
    rm_vars += [f"--spring-{k}" for k, _ in _skip_meta(mo.get("spring", {}).items())]
    rm_vars += ["--motion-quick", "--motion-control", "--motion-chip",
                "--motion-standard", "--motion-emphasized"]
    rm_body = "".join(f"    {v}: 0.01ms;\n" for v in rm_vars)
    out.append(
        "@media (prefers-reduced-motion: reduce) {\n"
        "  :root, :host {\n"
        f"{rm_body}"
        "  }\n}\n"
    )
    return "".join(out)


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description="Render design tokens into web CSS.")
    ap.add_argument("--check", action="store_true",
                    help="verify on-disk outputs are up to date; exit 1 if stale")
    args = ap.parse_args()

    tokens = json.loads(TOKENS_JSON.read_text(encoding="utf-8"))
    tokens_css = render_tokens_css(tokens)
    components_css = DIST_COMPONENTS.read_text(encoding="utf-8")

    targets: list[tuple[Path, str]] = [
        (DIST_TOKENS, tokens_css),
        (BACKEND_TOKENS, tokens_css),
        (BACKEND_COMPONENTS, components_css),
    ]

    if args.check:
        stale = [p for p, c in targets if not p.exists() or p.read_text(encoding="utf-8") != c]
        if stale:
            print("STALE web token outputs (run: uv run python ops/gen_web_tokens.py):")
            for p in stale:
                print(f"  - {p.relative_to(REPO)}")
            return 1
        print("web token outputs are up to date.")
        return 0

    for p, c in targets:
        _write(p, c)
        print(f"wrote {p.relative_to(REPO)} ({len(c)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
