import StyleDictionary from 'style-dictionary';

// ── Helpers ───────────────────────────────────────────────────────────────

function toSwiftId(segment) {
  if (/^\d+$/.test(segment)) return 's' + segment;
  return segment.replace(/-([a-z])/g, (_, letter) => letter.toUpperCase());
}

function swiftType(token) {
  switch (token.$type) {
    case 'dimension':
    case 'number': return 'CGFloat';
    case 'time': return 'Double';
    case 'string':
    case 'fontFamily': return 'String';
    default: return 'String';
  }
}

function swiftValue(token) {
  const v = token.value !== undefined ? token.value : (token.original?.$value ?? token.$value);
  if (v === undefined) {
    console.error('UNDEFINED value for token:', token.path.join('.'));
    return 'undefined';
  }
  switch (token.$type) {
    case 'dimension':
    case 'time':
      return parseFloat(v);
    case 'number':
      return v;
    case 'string':
    case 'fontFamily':
      return `"${v.replace(/"/g, '\\"')}"`;
    default:
      return `"${String(v).replace(/"/g, '\\"')}"`;
  }
}

// ── Custom format: Swift tokens ───────────────────────────────────────────

function resolveRef(value, dictionary) {
  if (typeof value !== 'string' || !value.startsWith('{') || !value.endsWith('}')) {
    return value;
  }
  const path = value.slice(1, -1).split('.');
  let node = dictionary.tokens;
  for (const part of path) {
    if (!node || !node[part]) {
      console.error('Unresolved reference:', value, 'at path:', path.join('.'));
      return value;
    }
    node = node[part];
  }
  // Recursively resolve (reference may point to another reference)
  const nextVal = node.$value !== undefined ? node.$value : node.value;
  return resolveRef(nextVal, dictionary);
}

StyleDictionary.registerFormat({
  name: 'kg/swift-tokens',
  format: ({ dictionary }) => {
    // Pre-resolve references for tokens with undefined value
    for (const token of dictionary.allTokens) {
      if (token.value === undefined && token.original?.$value !== undefined) {
        token.value = resolveRef(token.original.$value, dictionary);
      }
    }

    // Build a trie from token paths
    const root = {};
    for (const token of dictionary.allTokens) {
      let node = root;
      for (const part of token.path) {
        if (!node[part]) node[part] = {};
        node = node[part];
      }
      node.__token = token;
    }

    const lines = [
      '// GENERATED by Style Dictionary — DO NOT EDIT',
      'import Foundation',
      '',
      'public enum DesignTokens {',
    ];

    function emit(node, depth) {
      const indent = '    '.repeat(depth);
      const entries = Object.entries(node).sort(([a], [b]) => a.localeCompare(b));
      for (const [key, child] of entries) {
        if (key === '__token') continue;
        if (child.__token) {
          const token = child.__token;
          const name = toSwiftId(key);
          const type = swiftType(token);
          const value = swiftValue(token);
          lines.push(`${indent}public static let ${name}: ${type} = ${value}`);
        } else {
          lines.push(`${indent}public enum ${toSwiftId(key)} {`);
          emit(child, depth + 1);
          lines.push(`${indent}}`);
        }
      }
    }

    emit(root, 1);
    lines.push('}');
    return lines.join('\n') + '\n';
  },
});

// ── Configuration ─────────────────────────────────────────────────────────

export default {
  source: ['design-system/tokens.json'],
  platforms: {
    swift: {
      buildPath: 'ios/BooksBrowser/Models/',
      files: [{
        destination: 'DesignTokens.swift',
        format: 'kg/swift-tokens',
        filter: (token) => {
          // Exclude colors and web-only tokens
          if (token.path[0] === 'color') return false;
          if (token.path[0] === 'web-only') return false;
          return true;
        },
      }],
    },
  },
};
