import StyleDictionary from 'style-dictionary';

// ── Helpers ───────────────────────────────────────────────────────────────

// Leaf constant names: camelCase. Numeric leaves (space.scale "1".."10") → "s1".."s10".
function toSwiftId(segment) {
  if (/^\d+$/.test(segment)) return 's' + segment;
  return segment.replace(/-([a-z])/g, (_, letter) => letter.toUpperCase());
}

// Swift forbids type members named `Type`/`Protocol` (collide with the `.Type` /
// `.Protocol` metatype expressions). Remap such segments to safe, idiomatic names.
const SWIFT_RESERVED_ENUM = { Type: 'Typography', Protocol: 'ProtocolTokens' };

// Enum (namespace) segment names: PascalCase, idiomatic Swift.
// "steps" → "Steps", "z1" → "Z1", "tap-feedback" → "TapFeedback", "modal-swap" → "ModalSwap".
function toEnumName(segment) {
  const camel = segment.replace(/-([a-zA-Z0-9])/g, (_, c) => c.toUpperCase());
  const pascal = camel.charAt(0).toUpperCase() + camel.slice(1);
  return SWIFT_RESERVED_ENUM[pascal] ?? pascal;
}

function swiftType(token) {
  switch (token.$type) {
    case 'dimension':
    case 'number': return 'CGFloat';
    case 'time': return 'Double';
    case 'string':
    case 'fontFamily': return 'String';
    default: return 'String';
  }
}

function swiftValue(token) {
  const v = token.value !== undefined ? token.value : (token.original?.$value ?? token.$value);
  if (v === undefined) {
    console.error('UNDEFINED value for token:', token.path.join('.'));
    return 'undefined';
  }
  switch (token.$type) {
    case 'dimension':
    case 'time':
      return parseFloat(v);
    case 'number':
      return v;
    case 'string':
    case 'fontFamily':
      return `"${v.replace(/"/g, '\\"')}"`;
    default:
      return `"${String(v).replace(/"/g, '\\"')}"`;
  }
}

// ── Custom format: Swift tokens ───────────────────────────────────────────

function resolveRef(value, dictionary) {
  if (typeof value !== 'string' || !value.startsWith('{') || !value.endsWith('}')) {
    return value;
  }
  const path = value.slice(1, -1).split('.');
  let node = dictionary.tokens;
  for (const part of path) {
    if (!node || !node[part]) {
      console.error('Unresolved reference:', value, 'at path:', path.join('.'));
      return value;
    }
    node = node[part];
  }
  // Recursively resolve (reference may point to another reference)
  const nextVal = node.$value !== undefined ? node.$value : node.value;
  return resolveRef(nextVal, dictionary);
}

StyleDictionary.registerFormat({
  name: 'kg/swift-tokens',
  format: ({ dictionary }) => {
    // Pre-resolve references for tokens with undefined value
    for (const token of dictionary.allTokens) {
      if (token.value === undefined && token.original?.$value !== undefined) {
        token.value = resolveRef(token.original.$value, dictionary);
      }
    }

    // Build a trie from token paths
    const root = {};
    for (const token of dictionary.allTokens) {
      let node = root;
      for (const part of token.path) {
        if (!node[part]) node[part] = {};
        node = node[part];
      }
      node.__token = token;
    }

    const lines = [
      '// GENERATED by Style Dictionary — DO NOT EDIT',
      'import Foundation',
      '',
      'public enum DesignTokens {',
    ];

    function emit(node, depth) {
      const indent = '    '.repeat(depth);
      const entries = Object.entries(node).sort(([a], [b]) => a.localeCompare(b));
      for (const [key, child] of entries) {
        if (key === '__token') continue;
        if (child.__token) {
          const token = child.__token;
          const name = toSwiftId(key);
          const type = swiftType(token);
          const value = swiftValue(token);
          lines.push(`${indent}public static let ${name}: ${type} = ${value}`);
        } else {
          lines.push(`${indent}public enum ${toEnumName(key)} {`);
          emit(child, depth + 1);
          lines.push(`${indent}}`);
        }
      }
    }

    emit(root, 1);
    lines.push('}');
    return lines.join('\n') + '\n';
  },
});

// ── Name transform: full-path uniqueness ──────────────────────────────────
// Our format namespaces by token.path (nested enums), so it never reads
// token.name. But SD's default name = last path segment, which collides
// across branches (radius.semantic.control vs motion.duration.control) and
// spams warnings. Map name → full path so each token.name is unique. Purely
// cosmetic for log hygiene; does not affect emitted Swift.
StyleDictionary.registerTransform({
  name: 'kg/name-path',
  type: 'name',
  transform: (token) => token.path.map((p) => p.replace(/[^a-zA-Z0-9]/g, '_')).join('_'),
});

// ── Configuration ─────────────────────────────────────────────────────────

export default {
  source: ['design-system/tokens.json'],
  platforms: {
    swift: {
      transforms: ['kg/name-path'],
      buildPath: 'ios/BooksAndVocab/Models/',
      files: [{
        destination: 'DesignTokens.swift',
        format: 'kg/swift-tokens',
        filter: (token) => {
          // Exclude colors and web-only tokens
          if (token.path[0] === 'color') return false;
          if (token.path[0] === 'web-only') return false;
          // `radius.*` is absolute px for the web CSS only. iOS moved to the
          // dimensionless `roundness.*` plane, and emitting the px group into
          // Swift would leave a live re-entry path: someone could write
          // `AppRoundedRect(roundness: DesignTokens.Radius.Scale.md)` and put an
          // 8pt LENGTH into the t plane. The lint can't catch that (it only
          // rejects bare numerals), so the fix is to stop emitting it at all.
          if (token.path[0] === 'radius') return false;
          return true;
        },
      }],
    },
  },
};
